// Friendly opening-hook lines and educational summaries for popular stocks —
// the "you must have used a pendrive in school..." style the RM wants.
// Written for non-native English readers: short sentences, everyday products,
// no jargon. Aimed at letting a newbie RM confidently brief a client.

export interface StockHook {
  hook: string;
  whatTheyDo: string;
  howTheyMakeMoney: string;
  founded?: string;
  listedSince?: string;
  familiarProducts: string[];
  whyItMoves?: string[];
  malaysiaTie?: string;
  /** Main listed competitors (ticker symbols). Used by the Compare button. */
  competitors?: string[];
  noMalaysiaTie?: boolean;
}

export const STOCK_HOOKS: Record<string, StockHook> = {
  SNDK: {
    hook: "You must have used a pen drive during secondary school \u2014 Kingston, SanDisk, Seagate. SanDisk is the one that came back from the dead.",
    whatTheyDo: "SanDisk makes flash-memory storage \u2014 the chips inside pen drives, SD cards, and the SSDs that boot your laptop in seconds. After being absorbed by Western Digital in 2016, SanDisk was spun out as its own listed company again in 2025 to focus purely on the booming AI-storage market.",
    howTheyMakeMoney: "Sells NAND flash chips and consumer storage products (SD cards, pen drives, SSDs) to OEMs, retail, and data centres. The AI boom drives demand for high-capacity SSDs.",
    founded: "1988 (Sunnyvale, California)",
    listedSince: "NASDAQ since 2025 (spin-off from Western Digital)",
    familiarProducts: ["SanDisk pen drives", "SD / micro-SD cards", "Cruzer & iXpand USB drives", "SSDs for laptops", "Memory for AI data centres"],
    whyItMoves: ["NAND flash prices \u2014 when memory is in shortage, profits jump", "AI server demand for high-capacity storage", "Smartphone & PC sales cycles"],
    malaysiaTie: "Western Digital (SanDisk's former parent) operates a major hard-drive plant in Petaling Jaya \u2014 many of the drives Malaysians buy were partly built locally.",
    competitors: ["WDC", "MU"],
  },
  WDC: {
    hook: "If you bought an external hard disk at Lowyat Plaza in the last 15 years, there's a good chance it was a Western Digital.",
    whatTheyDo: "Western Digital makes the spinning hard drives and SSDs that store data \u2014 for laptops, gaming PCs, surveillance NVRs, and the warehouse-scale cloud servers behind every app you use.",
    howTheyMakeMoney: "Sells HDDs and SSDs to cloud providers (AWS, Azure, Google), PC makers, and consumers. Cloud orders are the biggest chunk.",
    founded: "1970",
    listedSince: "NASDAQ since 1978",
    familiarProducts: ["WD My Passport portable HDD", "WD Blue / Black / Red internal drives", "WD SSDs", "Storage for AWS, Azure, Google Cloud"],
    whyItMoves: ["Cloud-provider capex cycles", "HDD price levels", "AI demand for cheap mass storage"],
    malaysiaTie: "WD runs a massive HDD assembly plant in Petaling Jaya. One of Selangor's biggest tech employers.",
    competitors: ["MU", "SNDK"],
  },
  MU: {
    hook: "Inside every laptop, phone, and AI server is a memory chip. Micron is one of only three companies in the world that make them (the others are Samsung and SK Hynix).",
    whatTheyDo: "Micron designs and manufactures DRAM (the fast memory that runs apps) and NAND flash (the storage in your phone). Their HBM chips are critical for AI GPUs \u2014 Nvidia and AMD are both customers.",
    howTheyMakeMoney: "Sells memory chips to phone makers, PC OEMs, data centres, and automakers. HBM (high-bandwidth memory for AI) is the fastest-growing slice.",
    founded: "1978 (Boise, Idaho)",
    listedSince: "NASDAQ since 1984",
    familiarProducts: ["Crucial-brand consumer SSDs / RAM", "Memory inside iPhones, Galaxy phones", "HBM stacks inside Nvidia H100/B200 AI chips"],
    whyItMoves: ["Memory price cycles (DRAM and NAND)", "AI server demand for HBM", "Smartphone shipment trends"],
    malaysiaTie: "Micron has a back-end memory assembly & test facility in Penang Bayan Lepas \u2014 one of their key SEA operations.",
    competitors: ["WDC", "SNDK", "AMD"],
  },
  NVDA: {
    hook: "If you have ever seen 'GeForce' on a gaming laptop or heard 'AI chips' in the news \u2014 that is Nvidia.",
    whatTheyDo: "Nvidia designs the chips (GPUs) that power gaming graphics AND train every major AI model \u2014 including ChatGPT, Claude, and Gemini. Their H100 / B100 chips are the single most-fought-over hardware in the world right now.",
    howTheyMakeMoney: "Designs chips (doesn't make them \u2014 TSMC fabricates them) and sells to cloud giants (Microsoft, Meta, AWS, Google), AI startups, and PC builders. Data-centre revenue is now ~90% of the total.",
    founded: "1993",
    listedSince: "NASDAQ since 1999",
    familiarProducts: ["GeForce RTX gaming graphics cards", "Switch console chip (custom)", "Data-centre AI chips (H100, B200)", "Nvidia DRIVE for self-driving cars"],
    whyItMoves: ["AI capex spending from Big Tech (Meta, Microsoft, Google)", "Quarterly earnings \u2014 they regularly beat by huge margins", "Geopolitics \u2014 export bans to China hurt revenue"],
    malaysiaTie: "Nvidia partners with YTL Power to build a 100 MW AI data centre in Kulai, Johor \u2014 one of the biggest Nvidia GPU deployments in Southeast Asia.",
    competitors: ["AMD", "INTC", "AVGO", "QCOM", "MRVL"],
  },
  AMD: {
    hook: "AMD is the cheaper, fast-rising rival to Intel \u2014 the chips inside gaming PCs, PS5, Xbox, and now AI servers.",
    whatTheyDo: "AMD designs PC processors (Ryzen), server processors (EPYC), gaming console chips, and AI accelerators (Instinct MI300). They're the #2 AI chip company after Nvidia.",
    howTheyMakeMoney: "Sells chips to PC makers, server OEMs (HPE, Dell), and game console makers (Sony, Microsoft). MI300 AI accelerators are the new growth driver.",
    founded: "1969",
    listedSince: "NYSE since 1972",
    familiarProducts: ["Ryzen CPUs in laptops/desktops", "EPYC server processors", "PS5 and Xbox Series X chips", "Instinct AI accelerators"],
    whyItMoves: ["PC market cycle", "AI server share vs Nvidia", "Console refresh cycles"],
    malaysiaTie: "AMD has a major chip design + test facility in Penang Bayan Lepas. Hundreds of Malaysian engineers work there.",
    competitors: ["NVDA", "INTC", "AVGO", "QCOM"],
  },
  INTC: {
    hook: "The 'Intel Inside' sticker on every old laptop. Intel was the king of chips \u2014 now they're fighting to stay relevant in the AI era.",
    whatTheyDo: "Intel designs and makes PC and server processors, plus increasingly tries to compete in AI accelerators. They also have a chip foundry trying to compete with TSMC.",
    howTheyMakeMoney: "Sells CPUs to PC OEMs (Dell, HP, Lenovo) and server makers. They also fabricate chips for others (Intel Foundry Services).",
    founded: "1968",
    listedSince: "NASDAQ since 1971",
    familiarProducts: ["Intel Core i3 / i5 / i7 / i9 in laptops", "Xeon server processors", "Intel Arc graphics"],
    whyItMoves: ["Whether their new manufacturing process (Intel 18A) works", "AI chip share vs Nvidia/AMD", "Foundry business signing major clients"],
    malaysiaTie: "Intel has its largest assembly & test plant outside the US in Kulim, Kedah \u2014 operating since 1972. One of Malaysia's oldest American tech employers.",
    competitors: ["NVDA", "AMD", "TSM", "AVGO"],
  },
  AVGO: {
    hook: "You may never have heard of Broadcom, but every WiFi router, every iPhone, and most data-centre switches contain their chips.",
    whatTheyDo: "Broadcom designs networking chips (WiFi, Ethernet, 5G), custom AI accelerators for Google and Meta, and storage controllers. They also own VMware (cloud software).",
    howTheyMakeMoney: "Two halves \u2014 semiconductor sales (WiFi, switches, custom AI silicon for hyperscalers) and software (VMware, Symantec). High margins on both.",
    founded: "1961 (as HP's semiconductor arm, now headquartered in Palo Alto)",
    listedSince: "NASDAQ since 2009",
    familiarProducts: ["WiFi chips in iPhones + Android phones", "Set-top box chips for Astro/Unifi TV", "Custom AI chips for Google TPUs", "VMware enterprise software"],
    whyItMoves: ["AI custom-chip orders from Google/Meta", "iPhone cycle (they're an Apple supplier)", "VMware enterprise software renewals"],
    malaysiaTie: "Broadcom has design + back-end ops in Penang Bayan Lepas. Many Malaysians work as RF / chip engineers there.",
    competitors: ["NVDA", "MRVL", "QCOM", "INTC", "CSCO"],
  },
  MRVL: {
    hook: "Marvell makes the connectors that move your data inside the cloud at lightning speed. Without them, AI training would crawl.",
    whatTheyDo: "Marvell designs high-speed networking chips, optical interconnects, and custom silicon for AWS / Google / Microsoft data centres. The 'fibre between AI chips' is largely their business.",
    howTheyMakeMoney: "Sells custom and standard chips to cloud-provider data centres (~40%), 5G base stations (telcos), and enterprise storage.",
    founded: "1995",
    listedSince: "NASDAQ since 2000",
    familiarProducts: ["5G base-station chips (Verizon, AT&T)", "Storage controllers in enterprise SSDs", "Optical chips inside Meta/Google AI clusters"],
    whyItMoves: ["AI capex cycle (data-centre interconnect)", "5G rollout pace globally", "Custom-silicon wins with hyperscalers"],
    noMalaysiaTie: true,
    competitors: ["AVGO", "QCOM", "MU", "NVDA"],
  },
  QCOM: {
    hook: "Almost every Android phone in Malaysia uses a Qualcomm Snapdragon chip \u2014 and they collect royalties on every 5G call you make.",
    whatTheyDo: "Qualcomm designs the processors (Snapdragon) inside most Android phones, plus they own the patents for CDMA and 5G \u2014 so they collect licence fees on virtually every smartphone sold globally.",
    howTheyMakeMoney: "Two segments \u2014 chip sales (Snapdragon) and licensing royalties (every 5G phone, including iPhone, pays Qualcomm a cut).",
    founded: "1985",
    listedSince: "NASDAQ since 1991",
    familiarProducts: ["Snapdragon chips in Samsung Galaxy, Xiaomi, OPPO, Vivo phones", "5G modems in iPhones", "Snapdragon X-series laptop chips"],
    whyItMoves: ["Smartphone market growth", "Whether Apple switches its modem in-house", "Auto chip wins (Snapdragon Digital Chassis)"],
    noMalaysiaTie: true,
    competitors: ["AVGO", "MRVL", "NVDA", "AMD"],
  },
  TSM: {
    hook: "Apple, Nvidia, AMD all design chips. TSMC is the one Taiwanese company that actually makes them \u2014 they're the world's chip factory.",
    whatTheyDo: "TSMC is a pure-play foundry \u2014 they manufacture chips designed by others. Apple's M-series, every Nvidia AI GPU, AMD's Ryzen \u2014 all made in TSMC fabs. They have ~60% global share of advanced chip manufacturing.",
    howTheyMakeMoney: "Fabricates chips for hundreds of customers; the cutting-edge nodes (3nm, 2nm) carry premium pricing. Apple alone is ~25% of revenue.",
    founded: "1987",
    listedSince: "NYSE (ADR) since 1997 / TWSE since 1994",
    familiarProducts: ["Manufactures Apple A18 / M4 chips", "Manufactures Nvidia H100 / B200 AI chips", "Manufactures AMD Ryzen / Threadripper"],
    whyItMoves: ["Apple iPhone cycle", "AI capex cycle from Nvidia customers", "Taiwan-China geopolitical tensions"],
    malaysiaTie: "TSMC's customers (Apple, Nvidia) test/package some chips at OSAT plants in Penang (UTAC, ASE). TSMC itself is Taiwan-only.",
    competitors: ["INTC", "ASML", "AMAT", "LRCX"],
  },
  ASML: {
    hook: "You can't make modern chips without ASML. They're the only company in the world that builds the ultra-advanced EUV lithography machines.",
    whatTheyDo: "Dutch company that makes the giant machines (each costs $200M+) that print circuit patterns onto silicon wafers. TSMC, Samsung, and Intel all depend on ASML's EUV machines for advanced chips.",
    howTheyMakeMoney: "Sells lithography machines (~$300B order backlog) plus high-margin service contracts and spare parts.",
    founded: "1984 (Veldhoven, Netherlands)",
    listedSince: "NASDAQ + Euronext since 1995",
    familiarProducts: ["EUV machines used by TSMC, Samsung, Intel", "DUV machines for mature-node chip fabs"],
    whyItMoves: ["Chip-industry capex cycle (foundries buying machines)", "US export controls \u2014 restricts sales to China", "Backlog growth/shrink"],
    noMalaysiaTie: true,
    competitors: ["AMAT", "LRCX", "TSM"],
  },
  AAPL: {
    hook: "iPhone in your pocket, AirPods in your ears, MacBook on your desk \u2014 Apple is the most familiar tech name in Malaysia.",
    whatTheyDo: "Apple designs the iPhone, iPad, Mac, Apple Watch, and AirPods \u2014 and runs the App Store and Apple Pay that earn high-margin recurring revenue. Their hardware-plus-services model is the most profitable in the industry.",
    howTheyMakeMoney: "Hardware (~75% \u2014 iPhone alone is half of total revenue) plus Services (App Store cuts, iCloud, Apple Music, Apple Pay, ads). Services grow faster and carry higher margins.",
    founded: "1976",
    listedSince: "NASDAQ since 1980",
    familiarProducts: ["iPhone", "iPad", "MacBook", "AirPods", "Apple Watch", "Apple TV+ / Music / Pay"],
    whyItMoves: ["iPhone unit sales cycle", "Services growth (App Store)", "China demand (Apple's #2 market)"],
    malaysiaTie: "Apple suppliers Foxconn, Pegatron, and Inventec have factories in Malaysia (Johor, Penang) producing accessories and components.",
    competitors: ["MSFT", "GOOGL", "AMZN", "META"],
  },
  MSFT: {
    hook: "Every office computer you have ever used probably ran Windows and Microsoft Office. That's Microsoft. But the new growth story is Azure cloud and AI.",
    whatTheyDo: "Microsoft makes Windows, Office (Word/Excel/Teams), Azure cloud, Xbox, and owns LinkedIn + GitHub. They invested USD 13 billion in OpenAI (ChatGPT) \u2014 Azure AI is now the second-largest cloud-AI platform after AWS.",
    howTheyMakeMoney: "Three pillars \u2014 Productivity (Microsoft 365 subscriptions), Intelligent Cloud (Azure), and More Personal Computing (Windows, Xbox, Surface). Azure is the fastest-growing.",
    founded: "1975",
    listedSince: "NASDAQ since 1986",
    familiarProducts: ["Windows", "Microsoft 365 (Word, Excel, Teams)", "Xbox", "LinkedIn", "Azure cloud + Copilot AI"],
    whyItMoves: ["Azure growth rate (vs AWS, Google Cloud)", "Copilot AI adoption inside enterprises", "Office 365 seat counts"],
    malaysiaTie: "Microsoft committed USD 2.2 billion to open Malaysia data centres + train 200k Malaysians in AI \u2014 announced May 2024.",
    competitors: ["GOOGL", "AAPL", "AMZN", "ORCL", "CRM"],
  },
  GOOGL: {
    hook: "Google search, YouTube, Gmail, Google Maps \u2014 you use them every single day without thinking about it. Alphabet is the company behind all of them.",
    whatTheyDo: "Alphabet owns Google Search, YouTube, Android, Gmail, Maps, plus Google Cloud, Waymo self-driving, and DeepMind AI. Search ads still pay most of the bills, but YouTube + Cloud are growing the fastest.",
    howTheyMakeMoney: "Advertising on Search + YouTube is ~75% of revenue. Google Cloud is the second pillar. Devices (Pixel) and 'Other Bets' (Waymo) are small but strategic.",
    founded: "1998",
    listedSince: "NASDAQ since 2004",
    familiarProducts: ["Google Search", "YouTube", "Gmail", "Google Maps", "Android phones", "Google Cloud", "Pixel phones"],
    whyItMoves: ["Search ad market (faces ChatGPT competition)", "YouTube ad revenue & subscriptions", "Cloud growth vs AWS/Azure"],
    noMalaysiaTie: true,
    competitors: ["META", "MSFT", "AAPL", "AMZN"],
  },
  META: {
    hook: "Facebook, Instagram, WhatsApp \u2014 if you message your friends or scroll Reels at night, you are inside Meta's ecosystem.",
    whatTheyDo: "Meta owns Facebook, Instagram, WhatsApp, and Threads \u2014 about 4 billion monthly users between them. They make money from ads on the feeds. Their other bet is the metaverse: Quest VR headsets and Ray-Ban Meta smart glasses.",
    howTheyMakeMoney: "Nearly 100% from advertising on Facebook + Instagram + WhatsApp. They've cracked Reels monetisation; AI ad-targeting (Advantage+) is boosting margins.",
    founded: "2004",
    listedSince: "NASDAQ since 2012",
    familiarProducts: ["Facebook", "Instagram", "WhatsApp (used by every Malaysian)", "Threads", "Quest VR headsets", "Ray-Ban Meta smart glasses"],
    whyItMoves: ["Ad revenue growth (Reels + AI targeting)", "Reality Labs (VR) losses \u2014 how big they get", "Regulatory action in EU / US"],
    malaysiaTie: "Meta confirmed plans for a Malaysia data centre in Johor in 2024, and runs a regional engineering presence in Singapore that supports Malaysian users.",
    competitors: ["GOOGL", "NFLX", "AAPL", "AMZN"],
  },
  AMZN: {
    hook: "If you have ever streamed a movie on Prime Video, or your friend shopped on Amazon US \u2014 they made the box. But the real money is the cloud behind almost every app on your phone.",
    whatTheyDo: "Amazon runs the world's biggest online shopping site, Prime Video, and AWS \u2014 the cloud-server business that secretly powers Netflix, Airbnb, the CIA, and millions of small businesses. AWS does most of the company's profit.",
    howTheyMakeMoney: "Retail (low margins, huge volume) and AWS (very high margins, ~30% growth). Ads and Prime subs are also significant.",
    founded: "1994",
    listedSince: "NASDAQ since 1997",
    familiarProducts: ["Amazon.com shopping", "Prime Video", "Alexa / Echo speakers", "Kindle e-readers", "AWS cloud (behind your favourite apps)"],
    whyItMoves: ["AWS growth rate (currently re-accelerating)", "Retail margins improving", "Ad revenue growth"],
    malaysiaTie: "AWS opened its Malaysia Region (Selangor data centres) in 2024 \u2014 a USD 6 billion local investment over 15 years.",
    competitors: ["MSFT", "GOOGL", "WMT", "COST", "AAPL"],
  },
  TSLA: {
    hook: "Even if you have never seen a Tesla on Malaysian roads, you have heard about Elon Musk. Tesla is the EV brand the world watches.",
    whatTheyDo: "Tesla makes electric cars (Model 3 / Y / S / X / Cybertruck), home solar panels, and energy storage batteries (Megapack). They also bet big on full-self-driving software and humanoid robots (Optimus).",
    howTheyMakeMoney: "Selling cars (~85%), energy storage (growing fast \u2014 utilities buying Megapacks), and credits/services. The bull thesis is software (FSD) and robots, not cars.",
    founded: "2003",
    listedSince: "NASDAQ since 2010",
    familiarProducts: ["Model Y SUV", "Model 3 sedan", "Cybertruck", "Tesla Powerwall home battery", "Solar Roof"],
    whyItMoves: ["EV demand vs Chinese rivals (BYD, NIO)", "FSD / robotaxi progress", "Elon Musk headlines"],
    malaysiaTie: "Tesla opened its first Malaysian showroom in Bandar Utama in 2024. Some Model Y units sold in Malaysia are imported via Tesla Singapore.",
    competitors: ["NVDA"],
  },
  NFLX: {
    hook: "Late-night Netflix and chill \u2014 they have changed how you watch TV. Every Malaysian household has a subscription now.",
    whatTheyDo: "Netflix is the world's largest paid streaming service \u2014 270+ million subscribers globally. They both license content and increasingly produce their own (Stranger Things, Squid Game, Bridgerton).",
    howTheyMakeMoney: "Monthly subscription fees, with a new (cheaper) ad-supported tier introduced in 2022. International subs now bigger than US.",
    founded: "1997 (as DVD rental)",
    listedSince: "NASDAQ since 2002",
    familiarProducts: ["Netflix streaming", "Squid Game (Korean original)", "Stranger Things", "Money Heist (La Casa de Papel)"],
    whyItMoves: ["Subscriber additions (especially in Asia)", "Password-sharing crackdown impact", "Content slate hits/misses"],
    noMalaysiaTie: true,
    competitors: ["DIS", "META", "AMZN"],
  },
  NOW: {
    hook: "If you have ever filed a 'helpdesk ticket' at work \u2014 to fix a broken laptop, reset a password, or get IT help \u2014 there's a very good chance it was on ServiceNow. They're the boring-but-essential plumbing of corporate IT.",
    whatTheyDo: "ServiceNow runs the cloud platform that big companies use to manage internal workflows \u2014 IT helpdesks, HR requests, customer service, security alerts. About 85% of Fortune 500 companies pay them.",
    howTheyMakeMoney: "Charges enterprises a per-user, per-year subscription to use its Now platform \u2014 typically multi-year, multi-million-dollar contracts. Very sticky revenue (95%+ renewal rates).",
    founded: "2003 (San Diego, California)",
    listedSince: "NYSE since 2012",
    familiarProducts: ["IT helpdesk software at major Malaysian banks (Maybank, CIMB, Public Bank all use it)", "HR self-service portals at MNCs", "Workflow automation in government agencies"],
    whyItMoves: ["Enterprise software spend cycle", "AI features (NowAssist) driving more subscription value", "New customer wins from older competitors like SAP/Oracle"],
    malaysiaTie: "ServiceNow has a Malaysian office in KL and is widely deployed by Malaysian banks and telcos (Maybank, CIMB, Petronas, Astro, etc.) for their IT operations.",
    competitors: ["CRM", "ORCL", "WDAY", "ADBE", "MSFT"],
  },
  CRM: {
    hook: "If you have ever been called by a bank or insurance agent who 'has all your details on screen', they're probably using Salesforce.",
    whatTheyDo: "Salesforce is the world's #1 customer relationship management (CRM) software. Sales reps, marketers, and support agents use it to track every customer interaction. Owns Slack and Tableau too.",
    howTheyMakeMoney: "Enterprise software subscriptions \u2014 each sales rep, marketer, or support agent gets a paid seat. Average enterprise pays millions per year.",
    founded: "1999 (San Francisco)",
    listedSince: "NYSE since 2004",
    familiarProducts: ["Salesforce CRM (used by Maybank, AmBank, AIA, Allianz Malaysia)", "Slack messaging", "Tableau analytics", "MuleSoft integration"],
    whyItMoves: ["Enterprise IT spending", "AI agent (Agentforce) adoption", "Operating margin improvement"],
    malaysiaTie: "Salesforce has a Malaysian office in KL and is the CRM behind Maybank, AmBank, AIA Malaysia, Allianz Malaysia, and many other big local players.",
    competitors: ["NOW", "ORCL", "ADBE", "MSFT", "WDAY"],
  },
  ORCL: {
    hook: "Every big company keeps its data in a database. Oracle was the king of databases for 40 years \u2014 and now they're a fast-growing cloud + AI infrastructure player.",
    whatTheyDo: "Oracle sells the database software that runs banks, airlines, governments worldwide. They also run Oracle Cloud Infrastructure (OCI) \u2014 used by Nvidia, Microsoft, and OpenAI for AI training.",
    howTheyMakeMoney: "Database license fees + support, plus the fast-growing OCI cloud business. Cloud is now ~$25B/year and accelerating with AI deals.",
    founded: "1977",
    listedSince: "NYSE since 1986",
    familiarProducts: ["Oracle Database (runs most Malaysian banks' core systems)", "Oracle ERP / HCM", "Oracle Cloud Infrastructure"],
    whyItMoves: ["Cloud revenue growth (OCI vs AWS/Azure)", "AI infrastructure deals (Nvidia, OpenAI partnerships)", "Database renewal pricing"],
    malaysiaTie: "Oracle has a Malaysian office in KL and its database is the backbone of Maybank, CIMB, Bank Islam, and most Malaysian government systems.",
    competitors: ["MSFT", "CRM", "NOW", "IBM", "AMZN"],
  },
  ADBE: {
    hook: "If you have ever opened a PDF or seen 'Photoshop' on a designer's screen, you're using Adobe.",
    whatTheyDo: "Adobe makes the creative software designers and marketers depend on \u2014 Photoshop, Illustrator, Premiere, plus Acrobat (PDFs). They moved everything to monthly subscriptions in 2013.",
    howTheyMakeMoney: "Cloud subscriptions to Creative Cloud (Photoshop, etc), Document Cloud (Acrobat), and Experience Cloud (marketing analytics). 95%+ recurring revenue.",
    founded: "1982",
    listedSince: "NASDAQ since 1986",
    familiarProducts: ["Photoshop, Illustrator, Premiere (used by every Malaysian designer/marketer)", "Acrobat Reader / PDFs", "Adobe Express"],
    whyItMoves: ["AI features (Firefly) \u2014 defence vs Midjourney, ChatGPT image gen", "Subscription pricing power", "Creative Cloud subscriber count"],
    malaysiaTie: "Adobe has a regional Singapore office serving Malaysia. Adobe Creative Cloud is the standard at Malaysian design studios, agencies, and universities.",
    competitors: ["CRM", "MSFT", "ORCL", "NOW"],
  },
  IBM: {
    hook: "IBM was the original computing giant \u2014 they built the IBM PC, mainframes, and decades of corporate IT. Today they're betting on AI and hybrid cloud.",
    whatTheyDo: "IBM sells consulting services, cloud software (Red Hat OpenShift), AI (watsonx), and the mainframes that still run most banks, airlines, and government systems.",
    howTheyMakeMoney: "Three engines \u2014 software (Red Hat, watsonx AI), consulting (IT services), and infrastructure (mainframes still going strong with banks).",
    founded: "1911",
    listedSince: "NYSE since 1916",
    familiarProducts: ["IBM mainframes (runs most Malaysian banks' core)", "Red Hat Enterprise Linux", "watsonx AI platform", "IBM Consulting"],
    whyItMoves: ["Consulting growth (vs Accenture)", "Red Hat / hybrid cloud adoption", "watsonx AI traction with enterprises"],
    malaysiaTie: "IBM Malaysia is one of the oldest American tech operations here (since 1961). Maintains Cyberjaya campus + serves nearly all Malaysian banks.",
    competitors: ["MSFT", "ORCL", "CSCO"],
  },
  CSCO: {
    hook: "Every WiFi network at an office or airport probably runs on Cisco gear. Routers, switches, video calls (Webex) \u2014 they wire the corporate internet.",
    whatTheyDo: "Cisco makes the networking equipment (routers, switches, firewalls) that connects offices, data centres, and ISPs. They also own Webex (video conferencing) and Splunk (cybersecurity analytics).",
    howTheyMakeMoney: "Networking hardware + software subscriptions + recurring security and software products (Splunk acquisition pushes this higher).",
    founded: "1984",
    listedSince: "NASDAQ since 1990",
    familiarProducts: ["Cisco routers / switches (in every Malaysian office)", "Webex video conferencing", "Splunk cybersecurity", "Meraki WiFi"],
    whyItMoves: ["Enterprise IT capex cycle", "Splunk integration progress", "AI data-centre networking demand"],
    malaysiaTie: "Cisco has been in Malaysia since 1995 with a regional office in KL. Cisco gear is in most Malaysian banks, government departments, and ISPs.",
    competitors: ["ANET", "PANW", "CRWD", "AVGO"],
  },
  SNOW: {
    hook: "Companies generate huge amounts of data. Snowflake is the cloud warehouse where they put it all \u2014 and Wall Street loved them.",
    whatTheyDo: "Snowflake runs a cloud data platform \u2014 companies dump their data there to run analytics and AI. Built on top of AWS / Azure / Google Cloud.",
    howTheyMakeMoney: "Consumption-based pricing \u2014 customers pay for how much data they query. No long-term contracts, but most enterprises commit to multi-year deals.",
    founded: "2012",
    listedSince: "NYSE since 2020",
    familiarProducts: ["Snowflake Data Cloud (used by some Malaysian banks, fintechs, telcos for analytics)"],
    whyItMoves: ["Consumption growth (customers using more)", "Net retention rate (existing customers spending more)", "AI features (Cortex) driving incremental usage"],
    noMalaysiaTie: true,
    competitors: ["ORCL", "MSFT", "GOOGL"],
  },
  PLTR: {
    hook: "Palantir helps governments and big companies make sense of massive data \u2014 including counter-terrorism agencies, the US military, and large corporates.",
    whatTheyDo: "Palantir's software (Foundry, Gotham, AIP) ingests messy data from many sources and lets analysts make decisions on it \u2014 used by the CIA, US Army, defence contractors, and Fortune 500 companies.",
    howTheyMakeMoney: "Multi-million-dollar contracts with government (Gotham) and commercial enterprises (Foundry, AIP). Commercial growth is now outpacing government.",
    founded: "2003",
    listedSince: "NYSE since 2020",
    familiarProducts: ["Foundry (commercial \u2014 used by airlines, automakers)", "Gotham (defence \u2014 US military, intelligence)", "AIP (AI platform for enterprises)"],
    whyItMoves: ["US defence budget", "Commercial customer wins", "AIP (AI) revenue acceleration"],
    noMalaysiaTie: true,
    competitors: ["NOW", "CRM", "ORCL", "MSFT", "SNOW"],
  },
  V: {
    hook: "Every time you tap your card on a debit reader, swipe it abroad, or use Apple/Google Pay \u2014 Visa takes a tiny cut.",
    whatTheyDo: "Visa runs the world's largest card-payment network. They DON'T issue cards themselves (banks do) \u2014 they're the toll road in between, processing $13+ trillion of payments a year.",
    howTheyMakeMoney: "Tiny fee on every card transaction (typically 0.1-0.3%). Boring, predictable, hugely profitable. Cross-border tourism payments earn even higher fees.",
    founded: "1958 (BankAmericard)",
    listedSince: "NYSE since 2008",
    familiarProducts: ["Visa cards (Maybank, CIMB, HSBC, Public Bank issue them locally)", "Apple Pay / Google Pay transactions", "Cross-border payments"],
    whyItMoves: ["Global consumer spending", "Cross-border travel volumes", "Cash-to-card shift in emerging markets"],
    malaysiaTie: "Visa has a Malaysian office in KL. Most Malaysian credit/debit cards (Maybank, CIMB, HSBC, etc.) run on the Visa network.",
    competitors: ["MA", "PYPL"],
  },
  MA: {
    hook: "Visa's twin. Every time you use a Mastercard, they take their cut. Smaller than Visa but growing slightly faster.",
    whatTheyDo: "Mastercard runs the second-largest global card-payment network. Like Visa, they don't issue cards \u2014 they process the transactions between merchants and issuing banks.",
    howTheyMakeMoney: "Same model as Visa \u2014 tiny fee per transaction, very high margins. They've also pushed into B2B payments and 'value-added services' (cybersecurity, analytics).",
    founded: "1966",
    listedSince: "NYSE since 2006",
    familiarProducts: ["Mastercard credit/debit cards", "Maestro debit", "Mastercard contactless payments"],
    whyItMoves: ["Global consumer spending", "Cross-border travel", "Value-added services growth (faster than transaction fees)"],
    malaysiaTie: "Mastercard has an office in KL. Most Malaysian banks issue both Visa and Mastercard.",
    competitors: ["V", "PYPL"],
  },
  JPM: {
    hook: "The biggest US bank by market cap. If you have ever heard of 'Wall Street', JPMorgan is at the centre of it.",
    whatTheyDo: "JPMorgan Chase is the largest US bank by assets \u2014 retail banking, credit cards, investment banking (M&A advisory, trading), and asset management.",
    howTheyMakeMoney: "Net interest income from deposits/loans, plus fees from investment banking, trading, credit cards, and wealth management.",
    founded: "1799 (Manhattan Company); current form via 2000 Chase-JPMorgan merger",
    listedSince: "NYSE since 1969 (Chase Manhattan); current ticker since 2000",
    familiarProducts: ["Chase consumer banking", "JPMorgan Private Bank (wealth management)", "Investment banking advisory"],
    whyItMoves: ["US interest rates (higher rates = more net interest income)", "Investment banking deal volumes", "Loan loss provisions during recessions"],
    noMalaysiaTie: true,
    competitors: ["BAC", "GS", "MS", "WFC"],
  },
  WMT: {
    hook: "Walmart is the world's biggest retailer \u2014 like a giant Tesco or AEON, but US-focused. Cheap groceries, everyday essentials, and increasingly e-commerce.",
    whatTheyDo: "Walmart runs ~10,500 stores worldwide (mostly US) plus a fast-growing online business. Sam's Club is their warehouse-club arm.",
    howTheyMakeMoney: "Razor-thin margins on huge volume. Membership fees (Sam's Club, Walmart+) and ads on Walmart.com are higher-margin growth areas.",
    founded: "1962",
    listedSince: "NYSE since 1972",
    familiarProducts: ["Walmart stores (US)", "Sam's Club", "Walmart+ membership", "Walmart.com"],
    whyItMoves: ["US consumer spending", "E-commerce growth", "Margin expansion from ads + membership"],
    noMalaysiaTie: true,
    competitors: ["COST", "AMZN"],
  },
  COST: {
    hook: "Costco is the warehouse-club chain \u2014 you pay an annual membership for access to bulk groceries, electronics, and even gold bars at near-cost prices.",
    whatTheyDo: "Costco runs ~880 warehouse stores worldwide. They sell huge volumes at thin margins and make their actual profit on the annual membership fees (~$70/year).",
    howTheyMakeMoney: "Membership fees are nearly 100% of operating profit. Goods are sold near cost to keep members loyal. 90%+ renewal rate.",
    founded: "1976",
    listedSince: "NASDAQ since 1985",
    familiarProducts: ["Costco warehouse stores", "Kirkland Signature private label", "Costco gas stations"],
    whyItMoves: ["Membership renewal rate + fee increases", "Same-store sales growth", "International expansion (no Malaysia yet)"],
    noMalaysiaTie: true,
    competitors: ["WMT", "AMZN"],
  },
  KO: {
    hook: "Coca-Cola \u2014 the most recognised brand on Earth. From mamak stalls to KLCC restaurants, every Malaysian has had a Coke.",
    whatTheyDo: "Coca-Cola sells syrup concentrate to bottlers worldwide (they own brands, not bottling). Owns Sprite, Fanta, Minute Maid, Powerade, Costa Coffee, Smartwater, and dozens more.",
    howTheyMakeMoney: "Asset-light model \u2014 sells concentrate to bottlers, who handle the local production and distribution. Coke earns royalties + brand fees. Very high margins.",
    founded: "1886",
    listedSince: "NYSE since 1919",
    familiarProducts: ["Coca-Cola", "Sprite", "Fanta", "Minute Maid", "Powerade", "Schweppes (in some markets)"],
    whyItMoves: ["Global volume growth (especially emerging markets)", "Pricing power", "FX (US dollar strength hurts overseas profits)"],
    malaysiaTie: "Coca-Cola Bottlers (Malaysia) operates plants in Selangor + Sabah. Famously a long-time partner of many Malaysian restaurants and 7-Eleven.",
    competitors: ["PEP"],
  },
  MCD: {
    hook: "McDonald's \u2014 every Malaysian kid's first fast-food memory. Big Mac, McChicken, McSpicy.",
    whatTheyDo: "McDonald's runs ~40,000 restaurants worldwide \u2014 most owned by franchisees who pay McDonald's rent + royalties. The corporate entity is largely a real-estate and brand-licensing business.",
    howTheyMakeMoney: "Franchisee royalties + rent (they own the land under most stores), plus a smaller chunk from company-operated stores.",
    founded: "1940 (San Bernardino); franchised by Ray Kroc from 1955",
    listedSince: "NYSE since 1965",
    familiarProducts: ["Big Mac, McChicken, McSpicy", "McD Breakfast (Sausage McMuffin)", "McCaf\u00e9"],
    whyItMoves: ["Same-store sales growth globally", "Menu pricing power vs inflation", "Geopolitical / boycott risks (e.g. Middle East protests)"],
    malaysiaTie: "McDonald's Malaysia is operated by Gerbang Alaf Restaurants (owned by Saudi-linked Lionhorn). Over 300 stores across Malaysia.",
    competitors: ["SBUX"],
  },
  SBUX: {
    hook: "Starbucks \u2014 premium coffee chain. Once a luxury, now a daily routine for many urban Malaysians.",
    whatTheyDo: "Starbucks runs ~38,000 coffee shops worldwide \u2014 mostly company-owned. Famous for premium pricing, customisation (Frappuccino), and loyalty rewards.",
    howTheyMakeMoney: "Coffee + food + mobile-app loyalty programme. ~75% from company-owned stores; licensed stores (airports, supermarkets) add the rest.",
    founded: "1971",
    listedSince: "NASDAQ since 1992",
    familiarProducts: ["Frappuccino", "Pumpkin Spice Latte", "Starbucks Rewards", "Tumblers / merchandise"],
    whyItMoves: ["Same-store sales (especially China market)", "Margin expansion via app & rewards", "Coffee bean cost"],
    malaysiaTie: "Starbucks Malaysia is operated by Berjaya Food (BJFOOD on Bursa). Over 380 stores across Malaysia.",
    competitors: ["MCD"],
  },
  DIS: {
    hook: "Disney \u2014 Mickey Mouse, Marvel, Star Wars, Pixar, ESPN, and Hulu. They own most of the world's beloved characters.",
    whatTheyDo: "Disney owns theme parks, movie studios (Pixar, Marvel, Star Wars/Lucasfilm), streaming (Disney+, Hulu, ESPN+), and broadcast TV (ABC, ESPN).",
    howTheyMakeMoney: "Three segments \u2014 Experiences (parks, cruises), Entertainment (movies, streaming), Sports (ESPN). Parks are highest-margin.",
    founded: "1923",
    listedSince: "NYSE since 1957",
    familiarProducts: ["Disneyland / Disney World / Disney Cruise", "Marvel + Star Wars movies", "Disney+ streaming", "ESPN sports"],
    whyItMoves: ["Disney+ subscriber growth + ARPU", "Theme park attendance", "Box-office hits/misses"],
    noMalaysiaTie: true,
    competitors: ["NFLX", "META", "AAPL"],
  },
  LLY: {
    hook: "Eli Lilly makes Mounjaro and Zepbound \u2014 the latest blockbuster weight-loss / diabetes drugs that have taken the world by storm.",
    whatTheyDo: "Eli Lilly is a pharma giant. Best known today for GLP-1 drugs (Mounjaro for diabetes, Zepbound for weight loss) which Hollywood and tech executives can't get enough of. Also major in oncology and Alzheimer's.",
    howTheyMakeMoney: "Patented drug sales \u2014 Mounjaro/Zepbound alone could be $25B+/year. Patents expire eventually, so they invest heavily in pipeline.",
    founded: "1876",
    listedSince: "NYSE since 1952",
    familiarProducts: ["Mounjaro / Zepbound (GLP-1 weight-loss + diabetes)", "Verzenio (breast cancer)", "Trulicity (diabetes)"],
    whyItMoves: ["GLP-1 drug demand + supply (still rationed)", "Insurance coverage for weight-loss drugs", "Novo Nordisk (rival Ozempic maker) competition"],
    noMalaysiaTie: true,
    competitors: ["PFE", "MRK", "ABBV", "JNJ"],
  },
  UNH: {
    hook: "UnitedHealth is the largest US health insurer \u2014 they cover ~50 million Americans and own a vast medical-services business too.",
    whatTheyDo: "UnitedHealth has two halves \u2014 UnitedHealthcare (health insurance) and Optum (pharmacy benefits + clinics + healthcare data). Optum is the higher-growth, higher-margin side.",
    howTheyMakeMoney: "Insurance premiums (UnitedHealthcare) + pharmacy + clinical services (Optum).",
    founded: "1977",
    listedSince: "NYSE since 1984",
    familiarProducts: ["UnitedHealthcare insurance plans", "Optum Rx pharmacy benefits", "Optum Care clinics"],
    whyItMoves: ["US healthcare cost trends", "Medicare Advantage policies", "Optum growth"],
    noMalaysiaTie: true,
    competitors: ["LLY", "PFE"],
  },
  ANET: {
    hook: "Cloud companies need fast switches to connect their AI servers. Arista is the company that built the high-speed switch business that AWS, Microsoft, and Meta use.",
    whatTheyDo: "Arista Networks makes the high-speed Ethernet switches that move data inside hyperscale data centres. Their gear is the backbone of AWS, Microsoft Azure, Meta, and Oracle Cloud \u2014 moving the data between AI servers.",
    howTheyMakeMoney: "Sells networking switches + software subscriptions (EOS, CloudVision) to cloud-scale data centres. Half of revenue comes from just Microsoft + Meta.",
    founded: "2004 (Santa Clara, California)",
    listedSince: "NYSE since 2014",
    familiarProducts: ["Arista 7000 / 7800 data-centre switches", "EOS network operating system", "CloudVision management software"],
    whyItMoves: ["AI data-centre buildout (more switches per cluster)", "Customer concentration risk (Microsoft + Meta = ~40%)", "Cisco competition in enterprise"],
    noMalaysiaTie: true,
    competitors: ["CSCO", "AVGO"],
  },
  APH: {
    hook: "Amphenol makes the connectors and cables inside almost every electronic device \u2014 smartphones, cars, jet engines, AI servers. Boring but everywhere.",
    whatTheyDo: "Amphenol designs and manufactures interconnect products \u2014 high-frequency connectors, cables, sensors, antennas. Customers span aerospace, automotive, IT data centres, telecom, military.",
    howTheyMakeMoney: "Sells connectors + cables to OEMs across many industries. Highly diversified (no customer over 10% of revenue) \u2014 defensive characteristics.",
    founded: "1932",
    listedSince: "NYSE since 1991",
    familiarProducts: ["Connectors in iPhones, Galaxy phones", "Sensors in Tesla, BMW vehicles", "Cabling in Nvidia / AWS AI servers", "Aerospace connectors (Boeing, Airbus)"],
    whyItMoves: ["AI data-centre interconnect spend", "Auto cycle (especially EVs \u2014 more electronics per car)", "Aerospace recovery"],
    noMalaysiaTie: true,
  },
  AMAT: {
    hook: "Before TSMC can make Nvidia chips, they need machines from Applied Materials. AMAT is the world's largest chip-making equipment vendor.",
    whatTheyDo: "Applied Materials sells the tools that build chips \u2014 deposition, etching, ion implantation, inspection equipment. Every chip fab (TSMC, Samsung, Intel, Micron) buys from them.",
    howTheyMakeMoney: "Sells equipment (lumpy, big-ticket purchases) + recurring service contracts. Service revenue is growing as the installed base ages.",
    founded: "1967",
    listedSince: "NASDAQ since 1972",
    familiarProducts: ["Endura PVD deposition systems", "Producer CVD systems", "Centura etch systems"],
    whyItMoves: ["Chip-industry capex cycle", "China demand (US export restrictions hurt)", "Service-contract growth"],
    malaysiaTie: "Applied Materials has a manufacturing & R&D site in Penang, opened in 2018 to serve the regional chip industry.",
    competitors: ["LRCX", "ASML"],
  },
  LRCX: {
    hook: "Lam Research is the king of chip etching \u2014 the process that carves circuits onto silicon wafers. Together with AMAT and ASML, they're the trio that enables every chip.",
    whatTheyDo: "Lam Research makes etch and deposition equipment for chip manufacturing. Especially strong in NAND memory fabs \u2014 Samsung, SK Hynix, Micron are big customers.",
    howTheyMakeMoney: "Equipment sales + service. Memory makers buying capacity for HBM (AI memory) is the current tailwind.",
    founded: "1980",
    listedSince: "NASDAQ since 1984",
    familiarProducts: ["Kiyo etch systems", "ALTUS deposition systems", "VECTOR ALD systems"],
    whyItMoves: ["Memory chip capex cycle (Samsung, SK Hynix, Micron)", "HBM demand from AI chip makers", "China sales restrictions"],
    noMalaysiaTie: true,
    competitors: ["AMAT", "ASML"],
  },
  ABNB: {
    hook: "Airbnb \u2014 the homestay platform that changed how Malaysians travel. From Tokyo apartments to Penang heritage shophouses.",
    whatTheyDo: "Airbnb is the online marketplace that connects guests with hosts for short-term rentals. Operates in 220+ countries and territories, with millions of listings.",
    howTheyMakeMoney: "Takes a service fee from both hosts (3%) and guests (~14%) on every booking. Marketing is mostly word-of-mouth and SEO \u2014 low customer acquisition cost.",
    founded: "2008 (San Francisco)",
    listedSince: "NASDAQ since 2020",
    familiarProducts: ["Airbnb stays (homes, apartments, unique places)", "Airbnb Experiences", "Airbnb for Work"],
    whyItMoves: ["Cross-border travel demand", "Regulatory crackdowns (NYC, Barcelona limit short-term rentals)", "Long-stay growth (gig workers, digital nomads)"],
    malaysiaTie: "Airbnb has thousands of listings across Malaysia (Penang, KL, Langkawi, Kota Kinabalu). Especially popular for heritage stays and beach villas.",
  },
  SHOP: {
    hook: "Shopify is the Canadian e-commerce platform that powers a million small online stores \u2014 from KL boutiques to global D2C brands.",
    whatTheyDo: "Shopify lets anyone set up an online shop in minutes. They handle payments, shipping integration, inventory, even brick-and-mortar POS systems. Used by everyone from solopreneurs to Allbirds.",
    howTheyMakeMoney: "Monthly subscription fees + take rate on payments processed (Shopify Payments). Increasingly providing capital + logistics to merchants.",
    founded: "2006",
    listedSince: "NYSE since 2015",
    familiarProducts: ["Shopify store builder", "Shop Pay checkout", "Shopify POS for retail"],
    whyItMoves: ["E-commerce growth", "Take-rate on payments", "Merchant churn"],
    malaysiaTie: "Many Malaysian D2C brands run on Shopify. They have a regional office in Singapore serving Malaysia.",
    competitors: ["AMZN"],
  },
  UBER: {
    hook: "Uber \u2014 the ride-hailing app that changed how the world gets around. In Malaysia, they sold to Grab in 2018 but still huge globally.",
    whatTheyDo: "Uber runs the largest ride-hailing platform (Uber Rides), food delivery (Uber Eats), and freight matching (Uber Freight). Operates in 70+ countries.",
    howTheyMakeMoney: "Takes a cut (~20-30%) from every ride and delivery. Also Uber One subscription. Profit only became consistent in 2023.",
    founded: "2009",
    listedSince: "NYSE since 2019",
    familiarProducts: ["Uber rides", "Uber Eats food delivery", "Uber Freight"],
    whyItMoves: ["Trip volume growth", "Take-rate expansion via ads + Uber One", "Driver supply (wage pressure)"],
    malaysiaTie: "Uber exited Malaysia in 2018 (sold SEA operations to Grab). Currently has no direct Malaysian operations.",
  },
  PYPL: {
    hook: "PayPal \u2014 the original online payment service. Founded by Elon Musk and Peter Thiel. Still huge globally, but losing market share to newer rivals.",
    whatTheyDo: "PayPal runs an online payment processor + the consumer wallet (PayPal app, Venmo in US, Xoom for remittances). 400+ million active accounts.",
    howTheyMakeMoney: "Takes a percentage fee on payments processed. Branded checkout (the 'Pay with PayPal' button) is the cash cow.",
    founded: "1998",
    listedSince: "NASDAQ since 2015 (spun off from eBay)",
    familiarProducts: ["PayPal checkout", "Venmo (US peer-to-peer)", "Xoom international remittances"],
    whyItMoves: ["Branded checkout share vs Apple Pay, Stripe", "Active accounts trend (have been shrinking)", "Transaction margin"],
    noMalaysiaTie: true,
    competitors: ["V", "MA"],
  },
  WDAY: {
    hook: "Workday is the cloud HR + finance system that most big companies use to pay employees and manage budgets. Boring but mission-critical.",
    whatTheyDo: "Workday's cloud platform handles HR (payroll, benefits, recruiting, performance) and Finance (general ledger, procurement, planning). Used by 60% of Fortune 500.",
    howTheyMakeMoney: "Multi-year, per-employee subscription. Average contract is multi-million-dollar. High switching costs once deployed.",
    founded: "2005",
    listedSince: "NASDAQ since 2012",
    familiarProducts: ["Workday HCM (HR)", "Workday Financial Management", "Adaptive Planning"],
    whyItMoves: ["Enterprise IT budgets", "AI agents (Workday Illuminate) adoption", "International growth"],
    malaysiaTie: "Workday has Malaysian customers (Maybank, AIA Malaysia among others). Sold via partners + regional Singapore office.",
    competitors: ["ADBE", "ORCL", "CRM", "NOW", "INTU"],
  },
  INTU: {
    hook: "If you have ever used TurboTax or QuickBooks, that is Intuit. They own the US tax and small-business accounting software market.",
    whatTheyDo: "Intuit makes the dominant US consumer tax software (TurboTax), small-business accounting (QuickBooks), and personal finance (Mint, now Credit Karma). Also owns Mailchimp.",
    howTheyMakeMoney: "Annual subscriptions (TurboTax during tax season, QuickBooks year-round) plus payment processing fees on QuickBooks transactions.",
    founded: "1983",
    listedSince: "NASDAQ since 1993",
    familiarProducts: ["TurboTax", "QuickBooks Online", "Credit Karma", "Mailchimp"],
    whyItMoves: ["US tax-filing season (Q3 of fiscal year)", "Small-business creation trends", "AI assistant (Intuit Assist) adoption"],
    noMalaysiaTie: true,
    competitors: ["ADBE", "CRM"],
  },
  PG: {
    hook: "Procter & Gamble \u2014 the consumer goods giant behind Pampers, Pantene, Gillette, Tide, Olay. You probably have 5+ P&G products at home.",
    whatTheyDo: "P&G is the world's largest consumer goods company. Categories: baby care (Pampers), hair care (Pantene), shaving (Gillette), laundry (Tide), beauty (Olay, SK-II).",
    howTheyMakeMoney: "Sells branded consumer products through retail (supermarkets, e-commerce) + Amazon. Pricing power lets them pass on inflation.",
    founded: "1837 (Cincinnati, Ohio)",
    listedSince: "NYSE since 1890",
    familiarProducts: ["Pampers diapers", "Pantene shampoo", "Gillette razors", "Tide / Ariel laundry detergent", "Olay skincare", "SK-II (premium in Asia)"],
    whyItMoves: ["Pricing power vs commodity costs", "China demand (especially SK-II)", "Volume growth in emerging markets"],
    malaysiaTie: "P&G has had Malaysian operations since 1989, with a regional HQ in Bandar Sunway and a manufacturing plant in Bangi. P&G products are sold in every Malaysian supermarket.",
    competitors: ["KO", "PEP"],
  },
  JNJ: {
    hook: "Johnson & Johnson \u2014 the band-aid and baby shampoo company that grew into a pharma + medical-device giant.",
    whatTheyDo: "After spinning off consumer products (Kenvue) in 2023, J&J focuses on two segments: Innovative Medicine (cancer, immunology drugs) and MedTech (surgical robots, orthopaedic implants).",
    howTheyMakeMoney: "Patented drugs (Stelara, Darzalex, Tremfya) and medical devices (Ethicon, DePuy). Drugs are higher-margin but face patent cliffs.",
    founded: "1886",
    listedSince: "NYSE since 1944",
    familiarProducts: ["Stelara (autoimmune)", "Darzalex (cancer)", "Ethicon surgical instruments", "DePuy orthopaedic implants"],
    whyItMoves: ["Stelara patent expiration (biosimilars coming)", "Talc lawsuits (legal overhang)", "MedTech device sales"],
    noMalaysiaTie: true,
    competitors: ["PFE", "MRK", "ABBV", "LLY"],
  },
  PFE: {
    hook: "Pfizer \u2014 became a household name during COVID for their vaccine. Post-COVID, they're rebuilding with cancer drugs and a big oncology acquisition (Seagen).",
    whatTheyDo: "Pfizer is a major pharma \u2014 vaccines, cancer drugs, internal medicine. COVID vaccine (Comirnaty) + treatment (Paxlovid) brought $50B+ in 2022 then collapsed.",
    howTheyMakeMoney: "Patented drug sales. Major drugs: Eliquis (blood thinner \u2014 shared with BMS), Vyndaqel (heart), Ibrance (breast cancer), plus the Seagen cancer pipeline.",
    founded: "1849",
    listedSince: "NYSE since 1942",
    familiarProducts: ["Comirnaty (COVID vaccine)", "Paxlovid (COVID treatment)", "Eliquis (blood thinner)", "Ibrance (breast cancer)"],
    whyItMoves: ["Post-COVID revenue normalisation", "Seagen oncology pipeline payoff", "Patent cliffs late this decade"],
    noMalaysiaTie: true,
    competitors: ["MRK", "JNJ", "ABBV", "LLY"],
  },
  MRK: {
    hook: "Merck makes Keytruda \u2014 the world's best-selling drug. A cancer immunotherapy that's now used for 30+ cancer types.",
    whatTheyDo: "Merck's hit is Keytruda (cancer immunotherapy) \u2014 likely to be the highest-grossing drug in pharma history before its patent expires in 2028. Also vaccines (Gardasil, MMR) and animal health.",
    howTheyMakeMoney: "Keytruda alone is ~50% of pharma revenue (~$30B/yr). Plus Gardasil HPV vaccine, animal-health products.",
    founded: "1891",
    listedSince: "NYSE since 1946",
    familiarProducts: ["Keytruda (cancer immunotherapy)", "Gardasil 9 (HPV vaccine)", "Animal-health products"],
    whyItMoves: ["Keytruda patent cliff in 2028", "Pipeline replacements (subQ Keytruda, Lynparza, Welireg)", "China Gardasil sales (cyclical)"],
    noMalaysiaTie: true,
    competitors: ["PFE", "JNJ", "ABBV", "LLY"],
  },
  ABBV: {
    hook: "AbbVie \u2014 spun off from Abbott in 2013. Famous for Humira (autoimmune drug) which was the world's #1 drug for years. Now navigating life after Humira patents.",
    whatTheyDo: "AbbVie's flagships are Humira (used for arthritis, Crohn's), and successors Skyrizi + Rinvoq. Also Botox (yes, the wrinkle one \u2014 acquired from Allergan).",
    howTheyMakeMoney: "Patented drug sales. Humira's patent expired 2023 (biosimilars eating share). Skyrizi + Rinvoq are the new growth engines.",
    founded: "2013 (spun off from Abbott Laboratories)",
    listedSince: "NYSE since 2013",
    familiarProducts: ["Humira (autoimmune)", "Skyrizi (psoriasis)", "Rinvoq (autoimmune)", "Botox (cosmetic + medical)"],
    whyItMoves: ["Humira decline vs Skyrizi+Rinvoq replacement", "Botox demand (cyclical / discretionary)", "Pipeline execution"],
    noMalaysiaTie: true,
    competitors: ["PFE", "MRK", "LLY", "JNJ"],
  },
  BAC: {
    hook: "Bank of America \u2014 the #2 US bank. Massive retail branches across America, plus Merrill Lynch (wealth management).",
    whatTheyDo: "Bank of America runs retail banking (~4,000 branches), wealth management (Merrill Lynch), commercial banking, and investment banking (BofA Securities).",
    howTheyMakeMoney: "Net interest income on the huge US deposit base + fees (wealth management, investment banking). Sensitive to interest rates.",
    founded: "1904",
    listedSince: "NYSE since 1928",
    familiarProducts: ["BofA retail banking", "Merrill Lynch wealth management", "BofA Securities investment banking"],
    whyItMoves: ["US interest rates", "Credit-card loss rates", "Investment banking fee recovery"],
    noMalaysiaTie: true,
    competitors: ["JPM", "WFC", "MS", "GS"],
  },
  GS: {
    hook: "Goldman Sachs \u2014 the most prestigious investment bank on Wall Street. They advise on the biggest M&A deals and trade for global hedge funds.",
    whatTheyDo: "Goldman Sachs is mostly an investment bank \u2014 M&A advisory, equity/debt underwriting, trading desks (FICC, Equities), and asset management. They retreated from consumer banking (Marcus) in 2023.",
    howTheyMakeMoney: "Advisory and underwriting fees (lumpy), trading income (volatile), and asset management fees. M&A revival = profit boom.",
    founded: "1869",
    listedSince: "NYSE since 1999",
    familiarProducts: ["Goldman Sachs investment banking advisory", "Asset & Wealth Management", "Trading desks for hedge funds + corporates"],
    whyItMoves: ["M&A and IPO market activity", "Trading volatility", "Asset management AUM growth"],
    noMalaysiaTie: true,
    competitors: ["MS", "JPM", "BAC"],
  },
  WFC: {
    hook: "Wells Fargo \u2014 the third-biggest US bank. Lots of retail banking + mortgages. Spent years recovering from a 2016 fake-accounts scandal.",
    whatTheyDo: "Wells Fargo focuses on US consumer + commercial banking. They were under a Fed-imposed asset cap from 2018 (the cap was lifted in 2025).",
    howTheyMakeMoney: "Net interest income on US loans + deposit base. Mortgage origination is a key cyclical line.",
    founded: "1852",
    listedSince: "NYSE since 1962",
    familiarProducts: ["Wells Fargo retail banking", "Wells Fargo Home Mortgage", "Wells Fargo Advisors"],
    whyItMoves: ["US interest rates", "Asset cap regulatory progress (lifted 2025)", "Mortgage market"],
    noMalaysiaTie: true,
    competitors: ["BAC", "JPM", "MS"],
  },
  BLK: {
    hook: "BlackRock is the world's largest asset manager \u2014 they manage over USD 10 trillion of other people's money. Their ETF brand iShares is everywhere.",
    whatTheyDo: "BlackRock runs ETFs (iShares), index funds, active funds, alternative investments, and the Aladdin risk-management software. Most pension funds use Aladdin.",
    howTheyMakeMoney: "Tiny fees on enormous AUM (~$10T+). Aladdin software subscriptions add a high-margin recurring layer.",
    founded: "1988",
    listedSince: "NYSE since 1999",
    familiarProducts: ["iShares ETFs (used by retail + institutional)", "Aladdin portfolio management software", "Private markets (Global Infrastructure Partners)"],
    whyItMoves: ["Net inflows into ETFs (especially fixed income)", "Asset price moves (more AUM = more fees)", "Bitcoin ETF flows"],
    noMalaysiaTie: true,
    competitors: ["MS", "GS"],
  },
  "BRK.B": {
    hook: "Warren Buffett's holding company. Owns insurance (GEICO), railroads (BNSF), energy, plus a stock portfolio (Apple, Coca-Cola, Bank of America).",
    whatTheyDo: "Berkshire Hathaway is a conglomerate. Wholly owns ~60 businesses (GEICO insurance, BNSF railroad, Berkshire Hathaway Energy) AND holds a giant equities portfolio.",
    howTheyMakeMoney: "Operating businesses generate cash; insurance 'float' (premiums held before claims) is invested. Equity portfolio gains/losses now flow through earnings under new accounting rules.",
    founded: "1839 (Berkshire Cotton Mills); Buffett took over in 1965",
    listedSince: "NYSE since 1965 (Class A); Class B since 1996",
    familiarProducts: ["GEICO insurance", "BNSF Railway", "Dairy Queen", "See's Candies", "Apple shares (largest equity holding)"],
    whyItMoves: ["Equity portfolio (Apple, AmEx) performance", "Insurance underwriting profit", "Operating subsidiary results"],
    noMalaysiaTie: true,
    competitors: ["JPM", "BAC"],
  },
  NKE: {
    hook: "Nike \u2014 the world's biggest sportswear brand. Air Jordan sneakers, Just Do It campaigns, every football jersey.",
    whatTheyDo: "Nike designs and sells athletic footwear, apparel, and equipment. They don't manufacture \u2014 outsource to factories in Vietnam, Indonesia, China.",
    howTheyMakeMoney: "Wholesale (sports retailers) + Direct (Nike.com, Nike stores). Direct (DTC) is the higher-margin growth driver, except recent execution stumbled.",
    founded: "1964 (as Blue Ribbon Sports); renamed 1971",
    listedSince: "NYSE since 1980",
    familiarProducts: ["Air Jordan", "Nike Air Max", "Dri-FIT sports apparel", "Jordan brand"],
    whyItMoves: ["China demand (a big swing factor)", "DTC vs wholesale strategy progress", "Athlete endorsement / fashion cycles"],
    malaysiaTie: "Many Nike products sold in Malaysia are manufactured at suppliers in Vietnam + Indonesia. Nike Malaysia retail stores in major cities (KLCC, Mid Valley, Penang).",
  },
  PEP: {
    hook: "PepsiCo \u2014 not just Pepsi cola. They also own Lay's, Doritos, Cheetos, Quaker Oats, Gatorade. Snacks are bigger than drinks now.",
    whatTheyDo: "PepsiCo owns the world's biggest snacks portfolio (Frito-Lay), plus Pepsi and brands like Mountain Dew, Tropicana, Gatorade, Quaker. ~55% of revenue is snacks, not beverages.",
    howTheyMakeMoney: "Sells snacks + drinks globally. Frito-Lay snacks have higher margins than soda. Heavy investment in 'healthier' lines.",
    founded: "1965 (merger of Pepsi-Cola + Frito-Lay)",
    listedSince: "NYSE since 1965",
    familiarProducts: ["Pepsi cola", "Lay's potato chips", "Doritos", "Mountain Dew", "Gatorade", "Quaker Oats"],
    whyItMoves: ["Pricing power vs commodity cost inflation", "Snacks volume (recently soft)", "FX (US dollar strength hurts overseas)"],
    malaysiaTie: "PepsiCo Malaysia operates manufacturing in Bangi. Frito-Lay snacks and Pepsi widely sold across all Malaysian retail.",
    competitors: ["KO"],
  },
  BA: {
    hook: "Boeing \u2014 the iconic American aircraft maker. They build the 737, 787, and military jets. Recovering from major safety crises (737 MAX, Starliner).",
    whatTheyDo: "Boeing makes commercial aircraft (737, 787, 777X), defence systems (F-15, KC-46), and space (Starliner). MAX crashes (2018-19) and door-plug incident (2024) hurt their commercial business badly.",
    howTheyMakeMoney: "Sells aircraft + defence contracts + services. Recovery from safety crises means slow deliveries + thinner margins for now.",
    founded: "1916",
    listedSince: "NYSE since 1934",
    familiarProducts: ["737 MAX commercial jet (controversial)", "787 Dreamliner", "Apache helicopter (defence)", "Starliner spacecraft"],
    whyItMoves: ["Production rate of 737 MAX (still constrained)", "FAA safety reviews", "Defence contract wins"],
    noMalaysiaTie: true,
  },
  CAT: {
    hook: "Caterpillar \u2014 the bright yellow construction machines you see at any building site. From mining trucks to road graders, they make the heavy iron.",
    whatTheyDo: "Caterpillar builds construction equipment (excavators, dozers, loaders), mining trucks, diesel engines, and power generators. Heavy cyclical business \u2014 booms with construction + commodity prices.",
    howTheyMakeMoney: "Equipment sales + high-margin parts and service. Their Cat Financial arm provides financing to dealers/customers.",
    founded: "1925",
    listedSince: "NYSE since 1929",
    familiarProducts: ["CAT excavators / loaders", "CAT mining trucks", "Cat generator sets"],
    whyItMoves: ["Global construction cycle", "Commodity prices (mining demand)", "US infrastructure spending (IIJA bill)"],
    noMalaysiaTie: true,
  },
  XOM: {
    hook: "ExxonMobil \u2014 the largest US oil + gas company. Despite the energy transition, oil profits are still huge.",
    whatTheyDo: "ExxonMobil explores for + produces + refines + sells oil and gas products. They have major assets in the US (Permian Basin) and Guyana (huge offshore find). Acquired Pioneer Natural Resources in 2024.",
    howTheyMakeMoney: "Upstream (oil + gas production) when oil prices are high; Downstream (refining + petrochemicals) when crack spreads are wide. Diversified through the cycle.",
    founded: "1870 (as Standard Oil)",
    listedSince: "NYSE since 1972",
    familiarProducts: ["Exxon + Mobil-branded petrol stations", "Mobil 1 motor oil", "Esso lubricants"],
    whyItMoves: ["Crude oil price (Brent, WTI)", "Refining margins", "Capital discipline / dividend buybacks"],
    malaysiaTie: "ExxonMobil has had Malaysian operations since 1893. Operates offshore oil/gas fields off Terengganu + has refineries in Port Dickson. ExxonMobil Business Support Centre in KL employs thousands.",
    competitors: ["CVX"],
  },
  CVX: {
    hook: "Chevron \u2014 the #2 US oil company after Exxon. Smaller but more capital-disciplined; high dividend appeal.",
    whatTheyDo: "Chevron explores for + produces + refines oil and gas, with major assets in the Permian, Gulf of Mexico, Kazakhstan (Tengiz). Hess acquisition completed mid-2025 added a stake in Guyana.",
    howTheyMakeMoney: "Oil + gas production margins (upstream) + downstream refining/chemicals. Known for steady dividend returns to shareholders.",
    founded: "1879",
    listedSince: "NYSE since 1921",
    familiarProducts: ["Chevron + Texaco-branded fuel stations (US)", "Caltex (Asia-Pacific brand) \u2014 now sold to Chevron Malaysia"],
    whyItMoves: ["Crude oil prices", "Hess integration synergies", "Capital returns (dividend, buybacks)"],
    malaysiaTie: "Caltex (operated by Chevron Malaysia until 2020 spin-off to Penn-Co) \u2014 many Malaysians remember Caltex stations across the country.",
    competitors: ["XOM"],
  },
  VZ: {
    hook: "Verizon \u2014 the #1 US wireless carrier. ~120 million mobile subscribers, plus fibre internet (Fios) and 5G networks.",
    whatTheyDo: "Verizon Communications is mostly a US wireless + wireline telco. They built one of the largest 5G networks (especially mmWave) and serve consumer + enterprise customers.",
    howTheyMakeMoney: "Monthly wireless service revenue + sales of phones/plans. Stable recurring revenue, high dividend yield (>6%) \u2014 defensive utility-like stock.",
    founded: "2000 (merger of Bell Atlantic + GTE)",
    listedSince: "NYSE since 2000",
    familiarProducts: ["Verizon Wireless mobile plans", "Fios fibre internet (US)", "Verizon Business enterprise comms"],
    whyItMoves: ["Wireless subscriber adds (vs AT&T, T-Mobile)", "Capex on 5G rollout", "Dividend coverage"],
    noMalaysiaTie: true,
    competitors: ["T"],
  },
  COIN: {
    hook: "Coinbase \u2014 the most popular US crypto exchange. Tied to crypto prices: when Bitcoin pumps, Coinbase pumps.",
    whatTheyDo: "Coinbase runs a regulated US crypto exchange (consumer + institutional) and earns interest on USDC (the stablecoin co-owned with Circle).",
    howTheyMakeMoney: "Trading fees on every crypto buy/sell, plus interest income on USDC reserves. Subscription + services growing.",
    founded: "2012",
    listedSince: "NASDAQ since 2021",
    familiarProducts: ["Coinbase app (US retail)", "Coinbase Prime (institutional)", "USDC stablecoin (co-owned with Circle)"],
    whyItMoves: ["Bitcoin price", "Trading volume", "Crypto regulation (especially US)"],
    noMalaysiaTie: true,
  },
  CRWD: {
    hook: "CrowdStrike \u2014 the cybersecurity company that protects laptops and servers from hackers. After the July 2024 outage, they're rebuilding trust.",
    whatTheyDo: "CrowdStrike's Falcon platform protects endpoints (laptops, servers, cloud workloads) from cyberattacks. Used by ~70% of Fortune 500.",
    howTheyMakeMoney: "Annual subscriptions per endpoint. Module expansion (selling more capabilities to existing customers) is the growth lever.",
    founded: "2011",
    listedSince: "NASDAQ since 2019",
    familiarProducts: ["Falcon endpoint protection", "Falcon Cloud Security", "Falcon Identity"],
    whyItMoves: ["Enterprise cybersecurity budgets", "Module attach rate (selling more to same customer)", "Recovery from July 2024 IT outage incident"],
    noMalaysiaTie: true,
    competitors: ["PANW", "CSCO"],
  },
  PANW: {
    hook: "Palo Alto Networks \u2014 the #1 US enterprise cybersecurity company. Firewalls, cloud security, threat intelligence.",
    whatTheyDo: "Palo Alto sells firewall appliances (Strata), cloud security (Prisma), and security operations (Cortex). They've been pushing customers from one-off purchases to platform subscriptions.",
    howTheyMakeMoney: "Mix of hardware + software subscriptions + services. Platform consolidation is the bull thesis (one vendor, multiple security needs).",
    founded: "2005",
    listedSince: "NYSE since 2012",
    familiarProducts: ["PA-Series firewalls", "Prisma Cloud", "Cortex XDR"],
    whyItMoves: ["Enterprise cyber spend cycle", "Platformisation strategy (selling 3+ products per customer)", "Competitive dynamics with CRWD, ZS"],
    noMalaysiaTie: true,
    competitors: ["CRWD", "CSCO"],
  },
  SMCI: {
    hook: "Super Micro Computer \u2014 they build the AI servers that house Nvidia chips. Hot stock during the AI boom, then bumpy after an accounting controversy.",
    whatTheyDo: "Super Micro makes server systems \u2014 densely-packed boxes that hold Nvidia GPUs and CPUs for AI training. They customise faster than Dell/HPE.",
    howTheyMakeMoney: "Sells AI servers (low-margin hardware) to cloud customers + enterprises. Margin pressure when bigger competitors compete on price.",
    founded: "1993",
    listedSince: "NASDAQ since 2007",
    familiarProducts: ["Liquid-cooled GPU servers", "AI training racks", "Edge / IoT servers"],
    whyItMoves: ["AI server orders (Nvidia GPU allocation)", "Gross margin pressure", "Accounting / governance concerns (post-2024)"],
    noMalaysiaTie: true,
    competitors: ["DELL"],
  },
  DELL: {
    hook: "Dell \u2014 the PC and server company every Malaysian office knows. Now riding the AI server wave alongside Super Micro.",
    whatTheyDo: "Dell sells PCs (consumer + enterprise), servers (PowerEdge), storage (PowerStore), and AI servers. Storage came from EMC (acquired 2016).",
    howTheyMakeMoney: "PC + server hardware sales. AI server revenue + backlog has been the recent share-price driver.",
    founded: "1984",
    listedSince: "NYSE since 2018 (re-listed after going private in 2013)",
    familiarProducts: ["Dell XPS / Inspiron laptops", "PowerEdge servers", "PowerStore storage", "Dell AI Factory (with Nvidia)"],
    whyItMoves: ["AI server orders (Nvidia GPU allocation)", "PC refresh cycle", "Storage / VMware (EMC heritage) competition"],
    malaysiaTie: "Dell has a major presence in Penang since 1995 \u2014 their largest manufacturing & support operations outside the US. Cyberjaya has a Dell global services centre.",
    competitors: ["SMCI", "IBM"],
  },
  ENPH: {
    hook: "Enphase Energy \u2014 they make the microinverters that turn solar-panel DC into household AC. Solar boom names like this swing a lot with interest rates.",
    whatTheyDo: "Enphase makes microinverters (one per solar panel \u2014 safer than central inverters), batteries (IQ Battery), and EV chargers. Mostly residential solar.",
    howTheyMakeMoney: "Sells microinverters + batteries to installers + distributors. Each new rooftop installation is recurring hardware revenue.",
    founded: "2006",
    listedSince: "NASDAQ since 2012",
    familiarProducts: ["IQ8 microinverters", "IQ Battery 10", "IQ EV chargers"],
    whyItMoves: ["US interest rates (solar is heavily financed)", "Residential solar demand (recently weak)", "International expansion (Europe)"],
    noMalaysiaTie: true,
  },
};

/**
 * Render a friendly default hook when no curated entry exists.
 */
export function genericHook(longName: string, summary: string | null): string {
  if (!summary) {
    return `${longName} — let's break down what they do, how they make money, and where the stock could go.`;
  }
  const firstSentence = summary.split(/(?<=[.!?])\s+/)[0] ?? summary.slice(0, 220);
  return `${longName} — in one line: ${firstSentence}`;
}
