// Friendly opening-hook lines and educational summaries for popular stocks —
// the "you must have used a pendrive in school..." style the RM wants.
// Written for non-native English readers: short sentences, everyday products,
// no jargon. Aimed at letting a newbie RM confidently brief a client.

export interface StockHook {
  hook: string;
  whatTheyDo: string;
  howTheyMakeMoney: string;
  founded?: string;
  listedSince?: string;
  familiarProducts: string[];
  whyItMoves?: string[];
  malaysiaTie?: string;
  noMalaysiaTie?: boolean;
}

export const STOCK_HOOKS: Record<string, StockHook> = {
  SNDK: {
    hook: "You must have used a pen drive during secondary school \u2014 Kingston, SanDisk, Seagate. SanDisk is the one that came back from the dead.",
    whatTheyDo: "SanDisk makes flash-memory storage \u2014 the chips inside pen drives, SD cards, and the SSDs that boot your laptop in seconds. After being absorbed by Western Digital in 2016, SanDisk was spun out as its own listed company again in 2025 to focus purely on the booming AI-storage market.",
    howTheyMakeMoney: "Sells NAND flash chips and consumer storage products (SD cards, pen drives, SSDs) to OEMs, retail, and data centres. The AI boom drives demand for high-capacity SSDs.",
    founded: "1988 (Sunnyvale, California)",
    listedSince: "NASDAQ since 2025 (spin-off from Western Digital)",
    familiarProducts: ["SanDisk pen drives", "SD / micro-SD cards", "Cruzer & iXpand USB drives", "SSDs for laptops", "Memory for AI data centres"],
    whyItMoves: ["NAND flash prices \u2014 when memory is in shortage, profits jump", "AI server demand for high-capacity storage", "Smartphone & PC sales cycles"],
    malaysiaTie: "Western Digital (SanDisk's former parent) operates a major hard-drive plant in Petaling Jaya \u2014 many of the drives Malaysians buy were partly built locally.",
  },
  WDC: {
    hook: "If you bought an external hard disk at Lowyat Plaza in the last 15 years, there's a good chance it was a Western Digital.",
    whatTheyDo: "Western Digital makes the spinning hard drives and SSDs that store data \u2014 for laptops, gaming PCs, surveillance NVRs, and the warehouse-scale cloud servers behind every app you use.",
    howTheyMakeMoney: "Sells HDDs and SSDs to cloud providers (AWS, Azure, Google), PC makers, and consumers. Cloud orders are the biggest chunk.",
    founded: "1970",
    listedSince: "NASDAQ since 1978",
    familiarProducts: ["WD My Passport portable HDD", "WD Blue / Black / Red internal drives", "WD SSDs", "Storage for AWS, Azure, Google Cloud"],
    whyItMoves: ["Cloud-provider capex cycles", "HDD price levels", "AI demand for cheap mass storage"],
    malaysiaTie: "WD runs a massive HDD assembly plant in Petaling Jaya. One of Selangor's biggest tech employers.",
  },
  MU: {
    hook: "Inside every laptop, phone, and AI server is a memory chip. Micron is one of only three companies in the world that make them (the others are Samsung and SK Hynix).",
    whatTheyDo: "Micron designs and manufactures DRAM (the fast memory that runs apps) and NAND flash (the storage in your phone). Their HBM chips are critical for AI GPUs \u2014 Nvidia and AMD are both customers.",
    howTheyMakeMoney: "Sells memory chips to phone makers, PC OEMs, data centres, and automakers. HBM (high-bandwidth memory for AI) is the fastest-growing slice.",
    founded: "1978 (Boise, Idaho)",
    listedSince: "NASDAQ since 1984",
    familiarProducts: ["Crucial-brand consumer SSDs / RAM", "Memory inside iPhones, Galaxy phones", "HBM stacks inside Nvidia H100/B200 AI chips"],
    whyItMoves: ["Memory price cycles (DRAM and NAND)", "AI server demand for HBM", "Smartphone shipment trends"],
    malaysiaTie: "Micron has a back-end memory assembly & test facility in Penang Bayan Lepas \u2014 one of their key SEA operations.",
  },
  NVDA: {
    hook: "If you have ever seen 'GeForce' on a gaming laptop or heard 'AI chips' in the news \u2014 that is Nvidia.",
    whatTheyDo: "Nvidia designs the chips (GPUs) that power gaming graphics AND train every major AI model \u2014 including ChatGPT, Claude, and Gemini. Their H100 / B100 chips are the single most-fought-over hardware in the world right now.",
    howTheyMakeMoney: "Designs chips (doesn't make them \u2014 TSMC fabricates them) and sells to cloud giants (Microsoft, Meta, AWS, Google), AI startups, and PC builders. Data-centre revenue is now ~90% of the total.",
    founded: "1993",
    listedSince: "NASDAQ since 1999",
    familiarProducts: ["GeForce RTX gaming graphics cards", "Switch console chip (custom)", "Data-centre AI chips (H100, B200)", "Nvidia DRIVE for self-driving cars"],
    whyItMoves: ["AI capex spending from Big Tech (Meta, Microsoft, Google)", "Quarterly earnings \u2014 they regularly beat by huge margins", "Geopolitics \u2014 export bans to China hurt revenue"],
    malaysiaTie: "Nvidia partners with YTL Power to build a 100 MW AI data centre in Kulai, Johor \u2014 one of the biggest Nvidia GPU deployments in Southeast Asia.",
  },
  AMD: {
    hook: "AMD is the cheaper, fast-rising rival to Intel \u2014 the chips inside gaming PCs, PS5, Xbox, and now AI servers.",
    whatTheyDo: "AMD designs PC processors (Ryzen), server processors (EPYC), gaming console chips, and AI accelerators (Instinct MI300). They're the #2 AI chip company after Nvidia.",
    howTheyMakeMoney: "Sells chips to PC makers, server OEMs (HPE, Dell), and game console makers (Sony, Microsoft). MI300 AI accelerators are the new growth driver.",
    founded: "1969",
    listedSince: "NYSE since 1972",
    familiarProducts: ["Ryzen CPUs in laptops/desktops", "EPYC server processors", "PS5 and Xbox Series X chips", "Instinct AI accelerators"],
    whyItMoves: ["PC market cycle", "AI server share vs Nvidia", "Console refresh cycles"],
    malaysiaTie: "AMD has a major chip design + test facility in Penang Bayan Lepas. Hundreds of Malaysian engineers work there.",
  },
  INTC: {
    hook: "The 'Intel Inside' sticker on every old laptop. Intel was the king of chips \u2014 now they're fighting to stay relevant in the AI era.",
    whatTheyDo: "Intel designs and makes PC and server processors, plus increasingly tries to compete in AI accelerators. They also have a chip foundry trying to compete with TSMC.",
    howTheyMakeMoney: "Sells CPUs to PC OEMs (Dell, HP, Lenovo) and server makers. They also fabricate chips for others (Intel Foundry Services).",
    founded: "1968",
    listedSince: "NASDAQ since 1971",
    familiarProducts: ["Intel Core i3 / i5 / i7 / i9 in laptops", "Xeon server processors", "Intel Arc graphics"],
    whyItMoves: ["Whether their new manufacturing process (Intel 18A) works", "AI chip share vs Nvidia/AMD", "Foundry business signing major clients"],
    malaysiaTie: "Intel has its largest assembly & test plant outside the US in Kulim, Kedah \u2014 operating since 1972. One of Malaysia's oldest American tech employers.",
  },
  AVGO: {
    hook: "You may never have heard of Broadcom, but every WiFi router, every iPhone, and most data-centre switches contain their chips.",
    whatTheyDo: "Broadcom designs networking chips (WiFi, Ethernet, 5G), custom AI accelerators for Google and Meta, and storage controllers. They also own VMware (cloud software).",
    howTheyMakeMoney: "Two halves \u2014 semiconductor sales (WiFi, switches, custom AI silicon for hyperscalers) and software (VMware, Symantec). High margins on both.",
    founded: "1961 (as HP's semiconductor arm, now headquartered in Palo Alto)",
    listedSince: "NASDAQ since 2009",
    familiarProducts: ["WiFi chips in iPhones + Android phones", "Set-top box chips for Astro/Unifi TV", "Custom AI chips for Google TPUs", "VMware enterprise software"],
    whyItMoves: ["AI custom-chip orders from Google/Meta", "iPhone cycle (they're an Apple supplier)", "VMware enterprise software renewals"],
    malaysiaTie: "Broadcom has design + back-end ops in Penang Bayan Lepas. Many Malaysians work as RF / chip engineers there.",
  },
  MRVL: {
    hook: "Marvell makes the connectors that move your data inside the cloud at lightning speed. Without them, AI training would crawl.",
    whatTheyDo: "Marvell designs high-speed networking chips, optical interconnects, and custom silicon for AWS / Google / Microsoft data centres. The 'fibre between AI chips' is largely their business.",
    howTheyMakeMoney: "Sells custom and standard chips to cloud-provider data centres (~40%), 5G base stations (telcos), and enterprise storage.",
    founded: "1995",
    listedSince: "NASDAQ since 2000",
    familiarProducts: ["5G base-station chips (Verizon, AT&T)", "Storage controllers in enterprise SSDs", "Optical chips inside Meta/Google AI clusters"],
    whyItMoves: ["AI capex cycle (data-centre interconnect)", "5G rollout pace globally", "Custom-silicon wins with hyperscalers"],
    noMalaysiaTie: true,
  },
  QCOM: {
    hook: "Almost every Android phone in Malaysia uses a Qualcomm Snapdragon chip \u2014 and they collect royalties on every 5G call you make.",
    whatTheyDo: "Qualcomm designs the processors (Snapdragon) inside most Android phones, plus they own the patents for CDMA and 5G \u2014 so they collect licence fees on virtually every smartphone sold globally.",
    howTheyMakeMoney: "Two segments \u2014 chip sales (Snapdragon) and licensing royalties (every 5G phone, including iPhone, pays Qualcomm a cut).",
    founded: "1985",
    listedSince: "NASDAQ since 1991",
    familiarProducts: ["Snapdragon chips in Samsung Galaxy, Xiaomi, OPPO, Vivo phones", "5G modems in iPhones", "Snapdragon X-series laptop chips"],
    whyItMoves: ["Smartphone market growth", "Whether Apple switches its modem in-house", "Auto chip wins (Snapdragon Digital Chassis)"],
    noMalaysiaTie: true,
  },
  TSM: {
    hook: "Apple, Nvidia, AMD all design chips. TSMC is the one Taiwanese company that actually makes them \u2014 they're the world's chip factory.",
    whatTheyDo: "TSMC is a pure-play foundry \u2014 they manufacture chips designed by others. Apple's M-series, every Nvidia AI GPU, AMD's Ryzen \u2014 all made in TSMC fabs. They have ~60% global share of advanced chip manufacturing.",
    howTheyMakeMoney: "Fabricates chips for hundreds of customers; the cutting-edge nodes (3nm, 2nm) carry premium pricing. Apple alone is ~25% of revenue.",
    founded: "1987",
    listedSince: "NYSE (ADR) since 1997 / TWSE since 1994",
    familiarProducts: ["Manufactures Apple A18 / M4 chips", "Manufactures Nvidia H100 / B200 AI chips", "Manufactures AMD Ryzen / Threadripper"],
    whyItMoves: ["Apple iPhone cycle", "AI capex cycle from Nvidia customers", "Taiwan-China geopolitical tensions"],
    malaysiaTie: "TSMC's customers (Apple, Nvidia) test/package some chips at OSAT plants in Penang (UTAC, ASE). TSMC itself is Taiwan-only.",
  },
  ASML: {
    hook: "You can't make modern chips without ASML. They're the only company in the world that builds the ultra-advanced EUV lithography machines.",
    whatTheyDo: "Dutch company that makes the giant machines (each costs $200M+) that print circuit patterns onto silicon wafers. TSMC, Samsung, and Intel all depend on ASML's EUV machines for advanced chips.",
    howTheyMakeMoney: "Sells lithography machines (~$300B order backlog) plus high-margin service contracts and spare parts.",
    founded: "1984 (Veldhoven, Netherlands)",
    listedSince: "NASDAQ + Euronext since 1995",
    familiarProducts: ["EUV machines used by TSMC, Samsung, Intel", "DUV machines for mature-node chip fabs"],
    whyItMoves: ["Chip-industry capex cycle (foundries buying machines)", "US export controls \u2014 restricts sales to China", "Backlog growth/shrink"],
    noMalaysiaTie: true,
  },
  AAPL: {
    hook: "iPhone in your pocket, AirPods in your ears, MacBook on your desk \u2014 Apple is the most familiar tech name in Malaysia.",
    whatTheyDo: "Apple designs the iPhone, iPad, Mac, Apple Watch, and AirPods \u2014 and runs the App Store and Apple Pay that earn high-margin recurring revenue. Their hardware-plus-services model is the most profitable in the industry.",
    howTheyMakeMoney: "Hardware (~75% \u2014 iPhone alone is half of total revenue) plus Services (App Store cuts, iCloud, Apple Music, Apple Pay, ads). Services grow faster and carry higher margins.",
    founded: "1976",
    listedSince: "NASDAQ since 1980",
    familiarProducts: ["iPhone", "iPad", "MacBook", "AirPods", "Apple Watch", "Apple TV+ / Music / Pay"],
    whyItMoves: ["iPhone unit sales cycle", "Services growth (App Store)", "China demand (Apple's #2 market)"],
    malaysiaTie: "Apple suppliers Foxconn, Pegatron, and Inventec have factories in Malaysia (Johor, Penang) producing accessories and components.",
  },
  MSFT: {
    hook: "Every office computer you have ever used probably ran Windows and Microsoft Office. That's Microsoft. But the new growth story is Azure cloud and AI.",
    whatTheyDo: "Microsoft makes Windows, Office (Word/Excel/Teams), Azure cloud, Xbox, and owns LinkedIn + GitHub. They invested USD 13 billion in OpenAI (ChatGPT) \u2014 Azure AI is now the second-largest cloud-AI platform after AWS.",
    howTheyMakeMoney: "Three pillars \u2014 Productivity (Microsoft 365 subscriptions), Intelligent Cloud (Azure), and More Personal Computing (Windows, Xbox, Surface). Azure is the fastest-growing.",
    founded: "1975",
    listedSince: "NASDAQ since 1986",
    familiarProducts: ["Windows", "Microsoft 365 (Word, Excel, Teams)", "Xbox", "LinkedIn", "Azure cloud + Copilot AI"],
    whyItMoves: ["Azure growth rate (vs AWS, Google Cloud)", "Copilot AI adoption inside enterprises", "Office 365 seat counts"],
    malaysiaTie: "Microsoft committed USD 2.2 billion to open Malaysia data centres + train 200k Malaysians in AI \u2014 announced May 2024.",
  },
  GOOGL: {
    hook: "Google search, YouTube, Gmail, Google Maps \u2014 you use them every single day without thinking about it. Alphabet is the company behind all of them.",
    whatTheyDo: "Alphabet owns Google Search, YouTube, Android, Gmail, Maps, plus Google Cloud, Waymo self-driving, and DeepMind AI. Search ads still pay most of the bills, but YouTube + Cloud are growing the fastest.",
    howTheyMakeMoney: "Advertising on Search + YouTube is ~75% of revenue. Google Cloud is the second pillar. Devices (Pixel) and 'Other Bets' (Waymo) are small but strategic.",
    founded: "1998",
    listedSince: "NASDAQ since 2004",
    familiarProducts: ["Google Search", "YouTube", "Gmail", "Google Maps", "Android phones", "Google Cloud", "Pixel phones"],
    whyItMoves: ["Search ad market (faces ChatGPT competition)", "YouTube ad revenue & subscriptions", "Cloud growth vs AWS/Azure"],
    noMalaysiaTie: true,
  },
  META: {
    hook: "Facebook, Instagram, WhatsApp \u2014 if you message your friends or scroll Reels at night, you are inside Meta's ecosystem.",
    whatTheyDo: "Meta owns Facebook, Instagram, WhatsApp, and Threads \u2014 about 4 billion monthly users between them. They make money from ads on the feeds. Their other bet is the metaverse: Quest VR headsets and Ray-Ban Meta smart glasses.",
    howTheyMakeMoney: "Nearly 100% from advertising on Facebook + Instagram + WhatsApp. They've cracked Reels monetisation; AI ad-targeting (Advantage+) is boosting margins.",
    founded: "2004",
    listedSince: "NASDAQ since 2012",
    familiarProducts: ["Facebook", "Instagram", "WhatsApp (used by every Malaysian)", "Threads", "Quest VR headsets", "Ray-Ban Meta smart glasses"],
    whyItMoves: ["Ad revenue growth (Reels + AI targeting)", "Reality Labs (VR) losses \u2014 how big they get", "Regulatory action in EU / US"],
    malaysiaTie: "Meta confirmed plans for a Malaysia data centre in Johor in 2024, and runs a regional engineering presence in Singapore that supports Malaysian users.",
  },
  AMZN: {
    hook: "If you have ever streamed a movie on Prime Video, or your friend shopped on Amazon US \u2014 they made the box. But the real money is the cloud behind almost every app on your phone.",
    whatTheyDo: "Amazon runs the world's biggest online shopping site, Prime Video, and AWS \u2014 the cloud-server business that secretly powers Netflix, Airbnb, the CIA, and millions of small businesses. AWS does most of the company's profit.",
    howTheyMakeMoney: "Retail (low margins, huge volume) and AWS (very high margins, ~30% growth). Ads and Prime subs are also significant.",
    founded: "1994",
    listedSince: "NASDAQ since 1997",
    familiarProducts: ["Amazon.com shopping", "Prime Video", "Alexa / Echo speakers", "Kindle e-readers", "AWS cloud (behind your favourite apps)"],
    whyItMoves: ["AWS growth rate (currently re-accelerating)", "Retail margins improving", "Ad revenue growth"],
    malaysiaTie: "AWS opened its Malaysia Region (Selangor data centres) in 2024 \u2014 a USD 6 billion local investment over 15 years.",
  },
  TSLA: {
    hook: "Even if you have never seen a Tesla on Malaysian roads, you have heard about Elon Musk. Tesla is the EV brand the world watches.",
    whatTheyDo: "Tesla makes electric cars (Model 3 / Y / S / X / Cybertruck), home solar panels, and energy storage batteries (Megapack). They also bet big on full-self-driving software and humanoid robots (Optimus).",
    howTheyMakeMoney: "Selling cars (~85%), energy storage (growing fast \u2014 utilities buying Megapacks), and credits/services. The bull thesis is software (FSD) and robots, not cars.",
    founded: "2003",
    listedSince: "NASDAQ since 2010",
    familiarProducts: ["Model Y SUV", "Model 3 sedan", "Cybertruck", "Tesla Powerwall home battery", "Solar Roof"],
    whyItMoves: ["EV demand vs Chinese rivals (BYD, NIO)", "FSD / robotaxi progress", "Elon Musk headlines"],
    malaysiaTie: "Tesla opened its first Malaysian showroom in Bandar Utama in 2024. Some Model Y units sold in Malaysia are imported via Tesla Singapore.",
  },
  NFLX: {
    hook: "Late-night Netflix and chill \u2014 they have changed how you watch TV. Every Malaysian household has a subscription now.",
    whatTheyDo: "Netflix is the world's largest paid streaming service \u2014 270+ million subscribers globally. They both license content and increasingly produce their own (Stranger Things, Squid Game, Bridgerton).",
    howTheyMakeMoney: "Monthly subscription fees, with a new (cheaper) ad-supported tier introduced in 2022. International subs now bigger than US.",
    founded: "1997 (as DVD rental)",
    listedSince: "NASDAQ since 2002",
    familiarProducts: ["Netflix streaming", "Squid Game (Korean original)", "Stranger Things", "Money Heist (La Casa de Papel)"],
    whyItMoves: ["Subscriber additions (especially in Asia)", "Password-sharing crackdown impact", "Content slate hits/misses"],
    noMalaysiaTie: true,
  },
  NOW: {
    hook: "If you have ever filed a 'helpdesk ticket' at work \u2014 to fix a broken laptop, reset a password, or get IT help \u2014 there's a very good chance it was on ServiceNow. They're the boring-but-essential plumbing of corporate IT.",
    whatTheyDo: "ServiceNow runs the cloud platform that big companies use to manage internal workflows \u2014 IT helpdesks, HR requests, customer service, security alerts. About 85% of Fortune 500 companies pay them.",
    howTheyMakeMoney: "Charges enterprises a per-user, per-year subscription to use its Now platform \u2014 typically multi-year, multi-million-dollar contracts. Very sticky revenue (95%+ renewal rates).",
    founded: "2003 (San Diego, California)",
    listedSince: "NYSE since 2012",
    familiarProducts: ["IT helpdesk software at major Malaysian banks (Maybank, CIMB, Public Bank all use it)", "HR self-service portals at MNCs", "Workflow automation in government agencies"],
    whyItMoves: ["Enterprise software spend cycle", "AI features (NowAssist) driving more subscription value", "New customer wins from older competitors like SAP/Oracle"],
    malaysiaTie: "ServiceNow has a Malaysian office in KL and is widely deployed by Malaysian banks and telcos (Maybank, CIMB, Petronas, Astro, etc.) for their IT operations.",
  },
  CRM: {
    hook: "If you have ever been called by a bank or insurance agent who 'has all your details on screen', they're probably using Salesforce.",
    whatTheyDo: "Salesforce is the world's #1 customer relationship management (CRM) software. Sales reps, marketers, and support agents use it to track every customer interaction. Owns Slack and Tableau too.",
    howTheyMakeMoney: "Enterprise software subscriptions \u2014 each sales rep, marketer, or support agent gets a paid seat. Average enterprise pays millions per year.",
    founded: "1999 (San Francisco)",
    listedSince: "NYSE since 2004",
    familiarProducts: ["Salesforce CRM (used by Maybank, AmBank, AIA, Allianz Malaysia)", "Slack messaging", "Tableau analytics", "MuleSoft integration"],
    whyItMoves: ["Enterprise IT spending", "AI agent (Agentforce) adoption", "Operating margin improvement"],
    malaysiaTie: "Salesforce has a Malaysian office in KL and is the CRM behind Maybank, AmBank, AIA Malaysia, Allianz Malaysia, and many other big local players.",
  },
  ORCL: {
    hook: "Every big company keeps its data in a database. Oracle was the king of databases for 40 years \u2014 and now they're a fast-growing cloud + AI infrastructure player.",
    whatTheyDo: "Oracle sells the database software that runs banks, airlines, governments worldwide. They also run Oracle Cloud Infrastructure (OCI) \u2014 used by Nvidia, Microsoft, and OpenAI for AI training.",
    howTheyMakeMoney: "Database license fees + support, plus the fast-growing OCI cloud business. Cloud is now ~$25B/year and accelerating with AI deals.",
    founded: "1977",
    listedSince: "NYSE since 1986",
    familiarProducts: ["Oracle Database (runs most Malaysian banks' core systems)", "Oracle ERP / HCM", "Oracle Cloud Infrastructure"],
    whyItMoves: ["Cloud revenue growth (OCI vs AWS/Azure)", "AI infrastructure deals (Nvidia, OpenAI partnerships)", "Database renewal pricing"],
    malaysiaTie: "Oracle has a Malaysian office in KL and its database is the backbone of Maybank, CIMB, Bank Islam, and most Malaysian government systems.",
  },
  ADBE: {
    hook: "If you have ever opened a PDF or seen 'Photoshop' on a designer's screen, you're using Adobe.",
    whatTheyDo: "Adobe makes the creative software designers and marketers depend on \u2014 Photoshop, Illustrator, Premiere, plus Acrobat (PDFs). They moved everything to monthly subscriptions in 2013.",
    howTheyMakeMoney: "Cloud subscriptions to Creative Cloud (Photoshop, etc), Document Cloud (Acrobat), and Experience Cloud (marketing analytics). 95%+ recurring revenue.",
    founded: "1982",
    listedSince: "NASDAQ since 1986",
    familiarProducts: ["Photoshop, Illustrator, Premiere (used by every Malaysian designer/marketer)", "Acrobat Reader / PDFs", "Adobe Express"],
    whyItMoves: ["AI features (Firefly) \u2014 defence vs Midjourney, ChatGPT image gen", "Subscription pricing power", "Creative Cloud subscriber count"],
    malaysiaTie: "Adobe has a regional Singapore office serving Malaysia. Adobe Creative Cloud is the standard at Malaysian design studios, agencies, and universities.",
  },
  IBM: {
    hook: "IBM was the original computing giant \u2014 they built the IBM PC, mainframes, and decades of corporate IT. Today they're betting on AI and hybrid cloud.",
    whatTheyDo: "IBM sells consulting services, cloud software (Red Hat OpenShift), AI (watsonx), and the mainframes that still run most banks, airlines, and government systems.",
    howTheyMakeMoney: "Three engines \u2014 software (Red Hat, watsonx AI), consulting (IT services), and infrastructure (mainframes still going strong with banks).",
    founded: "1911",
    listedSince: "NYSE since 1916",
    familiarProducts: ["IBM mainframes (runs most Malaysian banks' core)", "Red Hat Enterprise Linux", "watsonx AI platform", "IBM Consulting"],
    whyItMoves: ["Consulting growth (vs Accenture)", "Red Hat / hybrid cloud adoption", "watsonx AI traction with enterprises"],
    malaysiaTie: "IBM Malaysia is one of the oldest American tech operations here (since 1961). Maintains Cyberjaya campus + serves nearly all Malaysian banks.",
  },
  CSCO: {
    hook: "Every WiFi network at an office or airport probably runs on Cisco gear. Routers, switches, video calls (Webex) \u2014 they wire the corporate internet.",
    whatTheyDo: "Cisco makes the networking equipment (routers, switches, firewalls) that connects offices, data centres, and ISPs. They also own Webex (video conferencing) and Splunk (cybersecurity analytics).",
    howTheyMakeMoney: "Networking hardware + software subscriptions + recurring security and software products (Splunk acquisition pushes this higher).",
    founded: "1984",
    listedSince: "NASDAQ since 1990",
    familiarProducts: ["Cisco routers / switches (in every Malaysian office)", "Webex video conferencing", "Splunk cybersecurity", "Meraki WiFi"],
    whyItMoves: ["Enterprise IT capex cycle", "Splunk integration progress", "AI data-centre networking demand"],
    malaysiaTie: "Cisco has been in Malaysia since 1995 with a regional office in KL. Cisco gear is in most Malaysian banks, government departments, and ISPs.",
  },
  SNOW: {
    hook: "Companies generate huge amounts of data. Snowflake is the cloud warehouse where they put it all \u2014 and Wall Street loved them.",
    whatTheyDo: "Snowflake runs a cloud data platform \u2014 companies dump their data there to run analytics and AI. Built on top of AWS / Azure / Google Cloud.",
    howTheyMakeMoney: "Consumption-based pricing \u2014 customers pay for how much data they query. No long-term contracts, but most enterprises commit to multi-year deals.",
    founded: "2012",
    listedSince: "NYSE since 2020",
    familiarProducts: ["Snowflake Data Cloud (used by some Malaysian banks, fintechs, telcos for analytics)"],
    whyItMoves: ["Consumption growth (customers using more)", "Net retention rate (existing customers spending more)", "AI features (Cortex) driving incremental usage"],
    noMalaysiaTie: true,
  },
  PLTR: {
    hook: "Palantir helps governments and big companies make sense of massive data \u2014 including counter-terrorism agencies, the US military, and large corporates.",
    whatTheyDo: "Palantir's software (Foundry, Gotham, AIP) ingests messy data from many sources and lets analysts make decisions on it \u2014 used by the CIA, US Army, defence contractors, and Fortune 500 companies.",
    howTheyMakeMoney: "Multi-million-dollar contracts with government (Gotham) and commercial enterprises (Foundry, AIP). Commercial growth is now outpacing government.",
    founded: "2003",
    listedSince: "NYSE since 2020",
    familiarProducts: ["Foundry (commercial \u2014 used by airlines, automakers)", "Gotham (defence \u2014 US military, intelligence)", "AIP (AI platform for enterprises)"],
    whyItMoves: ["US defence budget", "Commercial customer wins", "AIP (AI) revenue acceleration"],
    noMalaysiaTie: true,
  },
  V: {
    hook: "Every time you tap your card on a debit reader, swipe it abroad, or use Apple/Google Pay \u2014 Visa takes a tiny cut.",
    whatTheyDo: "Visa runs the world's largest card-payment network. They DON'T issue cards themselves (banks do) \u2014 they're the toll road in between, processing $13+ trillion of payments a year.",
    howTheyMakeMoney: "Tiny fee on every card transaction (typically 0.1-0.3%). Boring, predictable, hugely profitable. Cross-border tourism payments earn even higher fees.",
    founded: "1958 (BankAmericard)",
    listedSince: "NYSE since 2008",
    familiarProducts: ["Visa cards (Maybank, CIMB, HSBC, Public Bank issue them locally)", "Apple Pay / Google Pay transactions", "Cross-border payments"],
    whyItMoves: ["Global consumer spending", "Cross-border travel volumes", "Cash-to-card shift in emerging markets"],
    malaysiaTie: "Visa has a Malaysian office in KL. Most Malaysian credit/debit cards (Maybank, CIMB, HSBC, etc.) run on the Visa network.",
  },
  MA: {
    hook: "Visa's twin. Every time you use a Mastercard, they take their cut. Smaller than Visa but growing slightly faster.",
    whatTheyDo: "Mastercard runs the second-largest global card-payment network. Like Visa, they don't issue cards \u2014 they process the transactions between merchants and issuing banks.",
    howTheyMakeMoney: "Same model as Visa \u2014 tiny fee per transaction, very high margins. They've also pushed into B2B payments and 'value-added services' (cybersecurity, analytics).",
    founded: "1966",
    listedSince: "NYSE since 2006",
    familiarProducts: ["Mastercard credit/debit cards", "Maestro debit", "Mastercard contactless payments"],
    whyItMoves: ["Global consumer spending", "Cross-border travel", "Value-added services growth (faster than transaction fees)"],
    malaysiaTie: "Mastercard has an office in KL. Most Malaysian banks issue both Visa and Mastercard.",
  },
  JPM: {
    hook: "The biggest US bank by market cap. If you have ever heard of 'Wall Street', JPMorgan is at the centre of it.",
    whatTheyDo: "JPMorgan Chase is the largest US bank by assets \u2014 retail banking, credit cards, investment banking (M&A advisory, trading), and asset management.",
    howTheyMakeMoney: "Net interest income from deposits/loans, plus fees from investment banking, trading, credit cards, and wealth management.",
    founded: "1799 (Manhattan Company); current form via 2000 Chase-JPMorgan merger",
    listedSince: "NYSE since 1969 (Chase Manhattan); current ticker since 2000",
    familiarProducts: ["Chase consumer banking", "JPMorgan Private Bank (wealth management)", "Investment banking advisory"],
    whyItMoves: ["US interest rates (higher rates = more net interest income)", "Investment banking deal volumes", "Loan loss provisions during recessions"],
    noMalaysiaTie: true,
  },
  WMT: {
    hook: "Walmart is the world's biggest retailer \u2014 like a giant Tesco or AEON, but US-focused. Cheap groceries, everyday essentials, and increasingly e-commerce.",
    whatTheyDo: "Walmart runs ~10,500 stores worldwide (mostly US) plus a fast-growing online business. Sam's Club is their warehouse-club arm.",
    howTheyMakeMoney: "Razor-thin margins on huge volume. Membership fees (Sam's Club, Walmart+) and ads on Walmart.com are higher-margin growth areas.",
    founded: "1962",
    listedSince: "NYSE since 1972",
    familiarProducts: ["Walmart stores (US)", "Sam's Club", "Walmart+ membership", "Walmart.com"],
    whyItMoves: ["US consumer spending", "E-commerce growth", "Margin expansion from ads + membership"],
    noMalaysiaTie: true,
  },
  COST: {
    hook: "Costco is the warehouse-club chain \u2014 you pay an annual membership for access to bulk groceries, electronics, and even gold bars at near-cost prices.",
    whatTheyDo: "Costco runs ~880 warehouse stores worldwide. They sell huge volumes at thin margins and make their actual profit on the annual membership fees (~$70/year).",
    howTheyMakeMoney: "Membership fees are nearly 100% of operating profit. Goods are sold near cost to keep members loyal. 90%+ renewal rate.",
    founded: "1976",
    listedSince: "NASDAQ since 1985",
    familiarProducts: ["Costco warehouse stores", "Kirkland Signature private label", "Costco gas stations"],
    whyItMoves: ["Membership renewal rate + fee increases", "Same-store sales growth", "International expansion (no Malaysia yet)"],
    noMalaysiaTie: true,
  },
  KO: {
    hook: "Coca-Cola \u2014 the most recognised brand on Earth. From mamak stalls to KLCC restaurants, every Malaysian has had a Coke.",
    whatTheyDo: "Coca-Cola sells syrup concentrate to bottlers worldwide (they own brands, not bottling). Owns Sprite, Fanta, Minute Maid, Powerade, Costa Coffee, Smartwater, and dozens more.",
    howTheyMakeMoney: "Asset-light model \u2014 sells concentrate to bottlers, who handle the local production and distribution. Coke earns royalties + brand fees. Very high margins.",
    founded: "1886",
    listedSince: "NYSE since 1919",
    familiarProducts: ["Coca-Cola", "Sprite", "Fanta", "Minute Maid", "Powerade", "Schweppes (in some markets)"],
    whyItMoves: ["Global volume growth (especially emerging markets)", "Pricing power", "FX (US dollar strength hurts overseas profits)"],
    malaysiaTie: "Coca-Cola Bottlers (Malaysia) operates plants in Selangor + Sabah. Famously a long-time partner of many Malaysian restaurants and 7-Eleven.",
  },
  MCD: {
    hook: "McDonald's \u2014 every Malaysian kid's first fast-food memory. Big Mac, McChicken, McSpicy.",
    whatTheyDo: "McDonald's runs ~40,000 restaurants worldwide \u2014 most owned by franchisees who pay McDonald's rent + royalties. The corporate entity is largely a real-estate and brand-licensing business.",
    howTheyMakeMoney: "Franchisee royalties + rent (they own the land under most stores), plus a smaller chunk from company-operated stores.",
    founded: "1940 (San Bernardino); franchised by Ray Kroc from 1955",
    listedSince: "NYSE since 1965",
    familiarProducts: ["Big Mac, McChicken, McSpicy", "McD Breakfast (Sausage McMuffin)", "McCaf\u00e9"],
    whyItMoves: ["Same-store sales growth globally", "Menu pricing power vs inflation", "Geopolitical / boycott risks (e.g. Middle East protests)"],
    malaysiaTie: "McDonald's Malaysia is operated by Gerbang Alaf Restaurants (owned by Saudi-linked Lionhorn). Over 300 stores across Malaysia.",
  },
  SBUX: {
    hook: "Starbucks \u2014 premium coffee chain. Once a luxury, now a daily routine for many urban Malaysians.",
    whatTheyDo: "Starbucks runs ~38,000 coffee shops worldwide \u2014 mostly company-owned. Famous for premium pricing, customisation (Frappuccino), and loyalty rewards.",
    howTheyMakeMoney: "Coffee + food + mobile-app loyalty programme. ~75% from company-owned stores; licensed stores (airports, supermarkets) add the rest.",
    founded: "1971",
    listedSince: "NASDAQ since 1992",
    familiarProducts: ["Frappuccino", "Pumpkin Spice Latte", "Starbucks Rewards", "Tumblers / merchandise"],
    whyItMoves: ["Same-store sales (especially China market)", "Margin expansion via app & rewards", "Coffee bean cost"],
    malaysiaTie: "Starbucks Malaysia is operated by Berjaya Food (BJFOOD on Bursa). Over 380 stores across Malaysia.",
  },
  DIS: {
    hook: "Disney \u2014 Mickey Mouse, Marvel, Star Wars, Pixar, ESPN, and Hulu. They own most of the world's beloved characters.",
    whatTheyDo: "Disney owns theme parks, movie studios (Pixar, Marvel, Star Wars/Lucasfilm), streaming (Disney+, Hulu, ESPN+), and broadcast TV (ABC, ESPN).",
    howTheyMakeMoney: "Three segments \u2014 Experiences (parks, cruises), Entertainment (movies, streaming), Sports (ESPN). Parks are highest-margin.",
    founded: "1923",
    listedSince: "NYSE since 1957",
    familiarProducts: ["Disneyland / Disney World / Disney Cruise", "Marvel + Star Wars movies", "Disney+ streaming", "ESPN sports"],
    whyItMoves: ["Disney+ subscriber growth + ARPU", "Theme park attendance", "Box-office hits/misses"],
    noMalaysiaTie: true,
  },
  LLY: {
    hook: "Eli Lilly makes Mounjaro and Zepbound \u2014 the latest blockbuster weight-loss / diabetes drugs that have taken the world by storm.",
    whatTheyDo: "Eli Lilly is a pharma giant. Best known today for GLP-1 drugs (Mounjaro for diabetes, Zepbound for weight loss) which Hollywood and tech executives can't get enough of. Also major in oncology and Alzheimer's.",
    howTheyMakeMoney: "Patented drug sales \u2014 Mounjaro/Zepbound alone could be $25B+/year. Patents expire eventually, so they invest heavily in pipeline.",
    founded: "1876",
    listedSince: "NYSE since 1952",
    familiarProducts: ["Mounjaro / Zepbound (GLP-1 weight-loss + diabetes)", "Verzenio (breast cancer)", "Trulicity (diabetes)"],
    whyItMoves: ["GLP-1 drug demand + supply (still rationed)", "Insurance coverage for weight-loss drugs", "Novo Nordisk (rival Ozempic maker) competition"],
    noMalaysiaTie: true,
  },
  UNH: {
    hook: "UnitedHealth is the largest US health insurer \u2014 they cover ~50 million Americans and own a vast medical-services business too.",
    whatTheyDo: "UnitedHealth has two halves \u2014 UnitedHealthcare (health insurance) and Optum (pharmacy benefits + clinics + healthcare data). Optum is the higher-growth, higher-margin side.",
    howTheyMakeMoney: "Insurance premiums (UnitedHealthcare) + pharmacy + clinical services (Optum).",
    founded: "1977",
    listedSince: "NYSE since 1984",
    familiarProducts: ["UnitedHealthcare insurance plans", "Optum Rx pharmacy benefits", "Optum Care clinics"],
    whyItMoves: ["US healthcare cost trends", "Medicare Advantage policies", "Optum growth"],
    noMalaysiaTie: true,
  },
};

/**
 * Render a friendly default hook when no curated entry exists.
 */
export function genericHook(longName: string, summary: string | null): string {
  if (!summary) {
    return `${longName} — let's break down what they do, how they make money, and where the stock could go.`;
  }
  const firstSentence = summary.split(/(?<=[.!?])\s+/)[0] ?? summary.slice(0, 220);
  return `${longName} — in one line: ${firstSentence}`;
}
