// Web Push helper — server-only.
//
// Wraps the web-push library so callers can do `await sendPush(subscription,
// payload)` without re-configuring VAPID on every call.
//
// Required env vars:
//   VAPID_PUBLIC_KEY              — generated by scripts/generate-vapid.mjs
//   NEXT_PUBLIC_VAPID_PUBLIC_KEY  — same value, exposed to the client
//   VAPID_PRIVATE_KEY             — server-only secret
//   VAPID_SUBJECT                 — "mailto:you@example.com"

import webpush from "web-push";

let configured = false;

function configure(): boolean {
  if (configured) return true;
  const pub = process.env.VAPID_PUBLIC_KEY;
  const priv = process.env.VAPID_PRIVATE_KEY;
  const subj = process.env.VAPID_SUBJECT || "mailto:noreply@example.com";
  if (!pub || !priv) return false;
  webpush.setVapidDetails(subj, pub, priv);
  configured = true;
  return true;
}

export interface PushPayload {
  title: string;
  body: string;
  tag?: string;
  url?: string;     // page to open when the user taps the notification
  data?: any;
}

export interface PushTarget {
  endpoint: string;
  keys: { p256dh: string; auth: string };
}

export interface SendResult {
  ok: boolean;
  statusCode?: number;
  /** True if the push endpoint reported "Gone" (410 / 404) — caller should
   *  delete the subscription row. */
  gone?: boolean;
  error?: string;
}

export async function sendPush(target: PushTarget, payload: PushPayload): Promise<SendResult> {
  if (!configure()) return { ok: false, error: "VAPID keys not configured" };
  try {
    const res = await webpush.sendNotification(
      { endpoint: target.endpoint, keys: target.keys },
      JSON.stringify(payload),
      { TTL: 8 * 3600 }  // 8 hours — morning briefings shouldn't backlog
    );
    return { ok: true, statusCode: res.statusCode };
  } catch (e: any) {
    const code = e?.statusCode;
    const gone = code === 410 || code === 404;
    return { ok: false, statusCode: code, gone, error: e?.body || String(e?.message ?? e) };
  }
}
